// megafunction wizard: %ROM: 1-PORT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altsyncram 

// ============================================================
// File Name: image_rom.v
// Megafunction Name(s):
// 			altsyncram
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 23.1std.0 Build 991 11/28/2023 SC Lite Edition
// ************************************************************


//Copyright (C) 2023  Intel Corporation. All rights reserved.
//Your use of Intel Corporation's design tools, logic functions 
//and other software and tools, and any partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Intel Program License 
//Subscription Agreement, the Intel Quartus Prime License Agreement,
//the Intel FPGA IP License Agreement, or other applicable license
//agreement, including, without limitation, that your use is for
//the sole purpose of programming logic devices manufactured by
//Intel and sold by Intel or its authorized distributors.  Please
//refer to the applicable agreement for further details, at
//https://fpgasoftware.intel.com/eula.


//altsyncram ADDRESS_ACLR_A="NONE" CLOCK_ENABLE_INPUT_A="BYPASS" CLOCK_ENABLE_OUTPUT_A="BYPASS" DEVICE_FAMILY="Cyclone V" ENABLE_RUNTIME_MOD="NO" INIT_FILE="gatinho2_convertido.mif" NUMWORDS_A=19200 OPERATION_MODE="ROM" OUTDATA_ACLR_A="NONE" OUTDATA_REG_A="CLOCK0" WIDTH_A=8 WIDTH_BYTEENA_A=1 WIDTHAD_A=15 address_a clock0 q_a
//VERSION_BEGIN 23.1 cbx_altera_syncram_nd_impl 2023:11:29:19:33:06:SC cbx_altsyncram 2023:11:29:19:33:06:SC cbx_cycloneii 2023:11:29:19:33:06:SC cbx_lpm_add_sub 2023:11:29:19:33:06:SC cbx_lpm_compare 2023:11:29:19:33:06:SC cbx_lpm_decode 2023:11:29:19:33:06:SC cbx_lpm_mux 2023:11:29:19:33:05:SC cbx_mgl 2023:11:29:19:43:53:SC cbx_nadder 2023:11:29:19:33:06:SC cbx_stratix 2023:11:29:19:33:06:SC cbx_stratixii 2023:11:29:19:33:05:SC cbx_stratixiii 2023:11:29:19:33:06:SC cbx_stratixv 2023:11:29:19:33:05:SC cbx_util_mgl 2023:11:29:19:33:06:SC  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463



//lpm_decode DEVICE_FAMILY="Cyclone V" LPM_DECODES=3 LPM_WIDTH=2 data eq
//VERSION_BEGIN 23.1 cbx_cycloneii 2023:11:29:19:33:06:SC cbx_lpm_add_sub 2023:11:29:19:33:06:SC cbx_lpm_compare 2023:11:29:19:33:06:SC cbx_lpm_decode 2023:11:29:19:33:06:SC cbx_mgl 2023:11:29:19:43:53:SC cbx_nadder 2023:11:29:19:33:06:SC cbx_stratix 2023:11:29:19:33:06:SC cbx_stratixii 2023:11:29:19:33:05:SC  VERSION_END

//synthesis_resources = lut 4 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  image_rom_decode
	( 
	data,
	eq) /* synthesis synthesis_clearbox=1 */;
	input   [1:0]  data;
	output   [2:0]  eq;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [1:0]  data;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [1:0]  data_wire;
	wire  [2:0]  eq_node;
	wire  [3:0]  eq_wire;
	wire  [2:0]  w_anode106w;
	wire  [2:0]  w_anode120w;
	wire  [2:0]  w_anode129w;
	wire  [2:0]  w_anode138w;

	assign
		data_wire = data,
		eq = eq_node,
		eq_node = eq_wire[2:0],
		eq_wire = {w_anode138w[2], w_anode129w[2], w_anode120w[2], w_anode106w[2]},
		w_anode106w = {(w_anode106w[1] & (~ data_wire[1])), (w_anode106w[0] & (~ data_wire[0])), 1'b1},
		w_anode120w = {(w_anode120w[1] & (~ data_wire[1])), (w_anode120w[0] & data_wire[0]), 1'b1},
		w_anode129w = {(w_anode129w[1] & data_wire[1]), (w_anode129w[0] & (~ data_wire[0])), 1'b1},
		w_anode138w = {(w_anode138w[1] & data_wire[1]), (w_anode138w[0] & data_wire[0]), 1'b1};
endmodule //image_rom_decode


//lpm_mux DEVICE_FAMILY="Cyclone V" LPM_SIZE=3 LPM_WIDTH=8 LPM_WIDTHS=2 data result sel
//VERSION_BEGIN 23.1 cbx_lpm_mux 2023:11:29:19:33:05:SC cbx_mgl 2023:11:29:19:43:53:SC  VERSION_END

//synthesis_resources = lut 16 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  image_rom_mux
	( 
	data,
	result,
	sel) /* synthesis synthesis_clearbox=1 */;
	input   [23:0]  data;
	output   [7:0]  result;
	input   [1:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [23:0]  data;
	tri0   [1:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [7:0]  data0_wire;
	wire  [7:0]  data1_wire;
	wire  [7:0]  data2_wire;
	wire  [7:0]  result_node;

	assign
		data0_wire = (data[7:0] & {8{(~ sel[0])}}),
		data1_wire = (data[15:8] & {8{sel[0]}}),
		data2_wire = (data[23:16] & {8{sel[1]}}),
		result = result_node,
		result_node = (((data0_wire | data1_wire) & {8{(~ sel[1])}}) | data2_wire);
endmodule //image_rom_mux

//synthesis_resources = lut 20 M10K 20 reg 4 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION"} *)
module  image_rom_altsyncram
	( 
	address_a,
	clock0,
	q_a) /* synthesis synthesis_clearbox=1 */;
	input   [14:0]  address_a;
	input   clock0;
	output   [7:0]  q_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   clock0;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[1:0]	address_reg_a;
	reg	[1:0]	out_address_reg_a;
	wire  [2:0]   wire_rden_decode_eq;
	wire  [7:0]   wire_mux2_result;
	wire  [0:0]   wire_ram_block1a_0portadataout;
	wire  [0:0]   wire_ram_block1a_1portadataout;
	wire  [0:0]   wire_ram_block1a_2portadataout;
	wire  [0:0]   wire_ram_block1a_3portadataout;
	wire  [0:0]   wire_ram_block1a_4portadataout;
	wire  [0:0]   wire_ram_block1a_5portadataout;
	wire  [0:0]   wire_ram_block1a_6portadataout;
	wire  [0:0]   wire_ram_block1a_7portadataout;
	wire  [0:0]   wire_ram_block1a_8portadataout;
	wire  [0:0]   wire_ram_block1a_9portadataout;
	wire  [0:0]   wire_ram_block1a_10portadataout;
	wire  [0:0]   wire_ram_block1a_11portadataout;
	wire  [0:0]   wire_ram_block1a_12portadataout;
	wire  [0:0]   wire_ram_block1a_13portadataout;
	wire  [0:0]   wire_ram_block1a_14portadataout;
	wire  [0:0]   wire_ram_block1a_15portadataout;
	wire  [0:0]   wire_ram_block1a_16portadataout;
	wire  [0:0]   wire_ram_block1a_17portadataout;
	wire  [0:0]   wire_ram_block1a_18portadataout;
	wire  [0:0]   wire_ram_block1a_19portadataout;
	wire  [0:0]   wire_ram_block1a_20portadataout;
	wire  [0:0]   wire_ram_block1a_21portadataout;
	wire  [0:0]   wire_ram_block1a_22portadataout;
	wire  [0:0]   wire_ram_block1a_23portadataout;
	wire  [1:0]  address_a_sel;
	wire  [14:0]  address_a_wire;
	wire  [1:0]  rden_decode_addr_sel_a;

	// synopsys translate_off
	initial
		address_reg_a = 0;
	// synopsys translate_on
	always @ ( posedge clock0)
		  address_reg_a <= address_a_sel;
	// synopsys translate_off
	initial
		out_address_reg_a = 0;
	// synopsys translate_on
	always @ ( posedge clock0)
		  out_address_reg_a <= address_reg_a;
	image_rom_decode   rden_decode
	( 
	.data(rden_decode_addr_sel_a),
	.eq(wire_rden_decode_eq));
	image_rom_mux   mux2
	( 
	.data({wire_ram_block1a_23portadataout[0], wire_ram_block1a_22portadataout[0], wire_ram_block1a_21portadataout[0], wire_ram_block1a_20portadataout[0], wire_ram_block1a_19portadataout[0], wire_ram_block1a_18portadataout[0], wire_ram_block1a_17portadataout[0], wire_ram_block1a_16portadataout[0], wire_ram_block1a_15portadataout[0], wire_ram_block1a_14portadataout[0], wire_ram_block1a_13portadataout[0], wire_ram_block1a_12portadataout[0], wire_ram_block1a_11portadataout[0], wire_ram_block1a_10portadataout[0], wire_ram_block1a_9portadataout[0], wire_ram_block1a_8portadataout[0], wire_ram_block1a_7portadataout[0], wire_ram_block1a_6portadataout[0], wire_ram_block1a_5portadataout[0], wire_ram_block1a_4portadataout[0], wire_ram_block1a_3portadataout[0], wire_ram_block1a_2portadataout[0], wire_ram_block1a_1portadataout[0], wire_ram_block1a_0portadataout[0]}),
	.result(wire_mux2_result),
	.sel(out_address_reg_a));
	cyclonev_ram_block   ram_block1a_0
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[0]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_0portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_0.clk0_core_clock_enable = "ena0",
		ram_block1a_0.clk0_input_clock_enable = "none",
		ram_block1a_0.clk0_output_clock_enable = "none",
		ram_block1a_0.connectivity_checking = "OFF",
		ram_block1a_0.init_file = "gatinho2_convertido.mif",
		ram_block1a_0.init_file_layout = "port_a",
		ram_block1a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_0.mem_init0 = 2048'h47AB996EA2F2AAD7FC2C68106D2C71A8F78B91E0ABA48C5578F44667EB2FFC08A37A5FB4C27A230C6D77E250E64BEBAD56600471AE47BBD9AB4C0A65F652473BBD5739EC2343C9531B1CEBABEA2F940D45BF3D70983E03710A2AD23BFA301043AFF0E25371669E8ADC4CE5DBD163CC498DB6AF680DF17118BEA50B1DA440B8F2DE9AAE9675586E8C414E8AC9DEF3F7B08962E50C97C2EA5980B2BAABFD3BC4BC8A71D00C343A914F3973EB1AF4A13F01856061A3E4FBF697DDC8FBD4D68E19991C134A5F861973A0AD92C17DEAF842F082E5BD22AFE30FDABDD502FB2AD9FB456543AF6617FA18752AD689E30E88B566AA8959B4E4DB921DB53D02D04930C95D,
		ram_block1a_0.mem_init1 = 2048'h70183663E997F546AD4AE00097D1693BB4BC85D1A2DEDD40AB73AC97F71E0FFAB8641383D53DDDB3CE7AEA88FBBCBDE9A7C62335D224C68253888260AA773A39DDD1CCE0524E3C292F9CC64EC4312CD74299DCDF76B9E9C9E6E2952F4BD16A1CB15D227AC898BA11FDD3E1B550BBDE71BB77F735EEFDD4FF303A7083E3293D22EAD3AA2CAE4DFCC91575F15C6CC977FC23351B7DDC7D86D73F74738F51BC2E08A639E9AC8466D4E582E58A6A646E2E8664E43D47ECB14A7C685476601E05116E8035BF3362667D1479FA353596252E5DCDB2B4649253719FA52F6CE7F72F2D11A1DB7F7DCCD89C8F1780727376231C7F4E5BE9FAC1549D18C1B85416C1980EFA,
		ram_block1a_0.mem_init2 = 2048'h0234132745E06113D0109EBDFBE56DD35A0C737285F5EED31C0B1CF8A86E12C557AFC65FC1F33A38A9EF04C5382C4EC13CF101875F6BDDBDAC4D59246DB915F3317B94D1F2FC4E3260C53697D4A42AE1A92F646CDD2B35FD10172290E8C9DBFD09A77F540677AEE55D3CA51CF3C3814671CB1C0B19A357B7C0A988DD67C3DE2F8E6F0EBFFE02C186A08AAB017B82D7CC15A32E537CEAD704C0B57173C1C7133EDDD4382ADF6A8F8E6E9B110A0FECCA3405C9262105A30FA4DABC5A82EB7B9099F5B5FA65D89BD00978412C3CC4377B69B07542036D83044317BD6AFCC8251D0F927D1695365B61E4CC2733841EB771EF66EBE71D141CCB69BFF8B81E2283360D,
		ram_block1a_0.mem_init3 = 2048'h446BF8C08B9192CB070D666012DD59C61644A81552DDCD412D06C64BC97C4B0659FE4B6489F9A66C9D4D202011177BC1DABD390597586F6BDA400432C273A674B27B5892678FDFF0BB031C2EC41EC2D8CE7CDD84F66B8C9BADB8F21B2F97DDAD80E90BD905150092F6A5343E8F864DCCA21765B84F82FEBF197B7748F19BBDD76A890952B1EC1E52333EF352E5F16B3D7AB7A78A62E8FA8C1F3A4C54C81767DF2207ADD61082F2D72A9FFB3CC3BE9E82A9F4BF4A2CF9426A106AE2FCC866ECD48420DAF4332E213DDE8E80CE33ED812234DC0EBEEF483482BFCF0EFC8F49AE6E35F6A3D7B0328FE70AD875519F74EEB338D23C779E5BBA16DDB305ADEAFEBD49,
		ram_block1a_0.operation_mode = "rom",
		ram_block1a_0.port_a_address_clear = "none",
		ram_block1a_0.port_a_address_width = 13,
		ram_block1a_0.port_a_data_out_clear = "none",
		ram_block1a_0.port_a_data_out_clock = "clock0",
		ram_block1a_0.port_a_data_width = 1,
		ram_block1a_0.port_a_first_address = 0,
		ram_block1a_0.port_a_first_bit_number = 0,
		ram_block1a_0.port_a_last_address = 8191,
		ram_block1a_0.port_a_logical_ram_depth = 19200,
		ram_block1a_0.port_a_logical_ram_width = 8,
		ram_block1a_0.ram_block_type = "AUTO",
		ram_block1a_0.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_1
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[0]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_1portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_1.clk0_core_clock_enable = "ena0",
		ram_block1a_1.clk0_input_clock_enable = "none",
		ram_block1a_1.clk0_output_clock_enable = "none",
		ram_block1a_1.connectivity_checking = "OFF",
		ram_block1a_1.init_file = "gatinho2_convertido.mif",
		ram_block1a_1.init_file_layout = "port_a",
		ram_block1a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_1.mem_init0 = 2048'hAF59C9645E5971709830CAFE6366529750E704A7CE5716C81D91CBA60B23D26785085DF46CCFCC9BDA44A2AAC0C451E012BADD657F9AE7A4D54040B069D8FCED0D86133B6692B7211E34DF02A0262536165281100E82692A54A10EA57259B82032B2447E87359E680F07EA6E8D39A053531BB4DCB4BC30CE2BB93D766A30511091464E3D5B70BC167CEB0895A5CD88FDC78BD7862AA6B9453041A91915AF7529AEAE47BB70623CBA30AF32CF151A6EA94A25F610BE4695E3231D3454DE5453E0501B9A33C44B541317C3DB04E5D99636BBB6777F05DDED11302000DB43E8027FFC8311B874505603CEAE516F3B2E2CF2BA16B3DDF2D96BF59BAFCD0820804DE9,
		ram_block1a_1.mem_init1 = 2048'hEE647FF97BF723896764C949CE5AEEEEDA4DDB94BB07F5F628F3049F5CC0FFFDF6B574615208D8CB96BC9987E164EFA4F9A27D91D68813607B7299402881FA7C542A986675537FF4C040A723A07B3447A3E5C04494549759944EAFCE01923B7AAD7F7525B175821E18F819A911AAD3C41156F3161465873DD07C06AAADA4F3448268DF84D0102E439EA8793DFAB3DB2369209117C93828301BB8D50762875C83A76668C6C6E0537E4F081363102FB7304A1E45C71E7D6AB234A1DDBE1503B2B2AABD35E794D91DBF00E53E367BF50FF6180ED700233AAEF5066246D25667970E6ED78310AC4E4F06830F7BBC04617EB05BE85D19FB2EE06755E64C9E34AC65CC,
		ram_block1a_1.mem_init2 = 2048'h2E0F3C5EB6A72647B24025870973843CBFFEFC47F7C8723E612DA4E8905060F02005D61D728F32F92AF34A1D1B0E78EDFCD8E1A3E018B562EF867FB09164D94DC68BAA2B75925C04708F6C7EDDB54A878DA684B56D6057445A63C1C5957A6D22822E5618751C17712DC3A0652EB117101DDB5361D7751741B6B1646096AAB10233720A347380C685D08DBEBAD42FA501D1D5464AC4ABBCC605C73FF281C65933556F60C4CAD3FC1865030F4A55AC18F01B7F3A0AF508C47BCD3140BEBE578781D2A4787169A80E2D1D12FB8A9304FD0AB802734709348698C0AAABAC9548932F31AEC7CEC4D40FAF443FB49D1022DBAE67715E720A6745F6B3188777D08176D4,
		ram_block1a_1.mem_init3 = 2048'h0EAC802E984A170D33146227D12AAD2C348EF3BAABB0D8930CE727095015BF84B08D72000880984019F8B579CB7D4FBC266CF15DB89B38415F1890D267CD6FA851EB5C296807B707443C956C44D32E948D5422E7801B31A01D28A3F79A6FD7B0363B674C2EAD385FAD71F6D46061E4EED3DDB601FF00DCD21D3ADAAD6DCACBCE019E379A1A30E86C5E125A5A6558F8E17593DE042C7F540E3159C25F5C018B304EA7C8A446C013731A7B7A4A63593543A70716E15D14054E418D1BE255F0C9ADC4C93E525922A0F427F053849B1ADB0D25AB4E2D963DEE9D220C3A8A1D63E44C631B32A5CB957A80744DA6973AB8074B64325D2EE9142A0A965C5E6A6B7F734A,
		ram_block1a_1.operation_mode = "rom",
		ram_block1a_1.port_a_address_clear = "none",
		ram_block1a_1.port_a_address_width = 13,
		ram_block1a_1.port_a_data_out_clear = "none",
		ram_block1a_1.port_a_data_out_clock = "clock0",
		ram_block1a_1.port_a_data_width = 1,
		ram_block1a_1.port_a_first_address = 0,
		ram_block1a_1.port_a_first_bit_number = 1,
		ram_block1a_1.port_a_last_address = 8191,
		ram_block1a_1.port_a_logical_ram_depth = 19200,
		ram_block1a_1.port_a_logical_ram_width = 8,
		ram_block1a_1.ram_block_type = "AUTO",
		ram_block1a_1.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_2
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[0]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_2portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_2.clk0_core_clock_enable = "ena0",
		ram_block1a_2.clk0_input_clock_enable = "none",
		ram_block1a_2.clk0_output_clock_enable = "none",
		ram_block1a_2.connectivity_checking = "OFF",
		ram_block1a_2.init_file = "gatinho2_convertido.mif",
		ram_block1a_2.init_file_layout = "port_a",
		ram_block1a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_2.mem_init0 = 2048'hE0F9C66FFF990857EB7FC67894660F0F47674D80281610378151C18083C1FB7C56FE83BD2F3FEB80386BAD1CC203A5D58FC41B349EDF0F43C2580E6E1DC1F06759F3A7B44EA007768EE086B8ED714D0C4F1E7117E831B80D5AC879ACB0C103C9457D4B69F2CA0E072007200DDF3820899F60CA64A8E42B73DC62D0F0113CE270E7A800EAA29D1A2A3061F21A1A6DEC3F1DF0604036D32A6013AF2580906AD8EC179E4C3468C63622382C165D5DA0E6E04CEA207F7D4E02E0E3ABA4A8F56C3C045FC01667AF332ACF3422210C1F12B2134A6C14FBB2564BC6444ED38F4012464BE1EC8DFE1A32F076833C5FD43E99FD7225B4F2E670E6C3352813CB56BDB857D1,
		ram_block1a_2.mem_init1 = 2048'h9613E775129986178F5257DE7E2531041FFF0209F193B1206380AA0B53A0DE036E8BCBF6715F987B9E9E7DDB18E0B367E5305E8F16C31F1C1CFDBEF8122464849D2DFAEB9054ED1C63D5811881C4EC6BE20C32C28F294905A88EA5F7500EA1C720809378C5DD0EB10A50A92CC79564ECC005D9080448028006D4929B4B96B43C3DE785DA248053C1902087208C7969FF8CA1EF71F715CDD78FB8E77E209498E479E031CD19195F4ACA17832F75332C509E870731B0215D70F5AB0422F76F4C7A6C94C21F0FC1D97C00218BFB6D934C1D17EF964E8EBB469598E27F5E568EF9D27269ED00EB9FFE490E733E8C0A6100F05B8C64FEA06AEEDED6267B78D399DDC7,
		ram_block1a_2.mem_init2 = 2048'hA5697032F213CC32F418F88F3DA1C92356A215048E0B999716B42E2B67EB338B78D474B92ACC7BB36DDE09DD0BE479ED38B3F213DC00D703A3D10B1FF282679D7A0B444A7C1DC404130F3F8123CFBC8F61A0C246924FA87F80BD6BF7E35419F95C0A7970254D5DC4C132B10F0691BE73C3836BA8B05E97FB24A99FDE7F556313C59927B66AF6009EC633148F98E5926AE6A8E522BDA33BC0075B3CE0F12A10EFC63B63183D79567DBBF9D8C27A451974986B1747710959E3CFFC2513C16B22493A04F802EC1D5D7E1152C526E3CFBEC5837FE49FA91F8768E5C2D1EF46BC689AFA38F1B34232DE4CCE3BB7CAFE24200F822E76E25D9FE70E776B7DF10898F56D,
		ram_block1a_2.mem_init3 = 2048'h87CF100BF7C751BEA9252998F64848521B309389178AC876B3E199D47ACA7A97A808855B53859AE05F4C0E4B888F4060135F241E1BCB7B4C567A5C145D5F907B41E3934CFC35E780533106AC0CD8BB639E3FDE6D4FEB30BCCD01D70B0DAAC6AED21B05CB87F157B996C3F3E1C22E7132C7FE27C6A4EF4BF98673801A232D7B3E9CDCC6276760E605D29D5FFDF71C1E271A6A6FD6141A1844EF66D546052A5D81D3E4B11925BBF1CC5EC453E42EC84EDF2042634CA79F1975D867F4446C91D1A6B82017C1547CDFF773651E267C0DA4F30D74909B901D4AC490644CDACCA1BD09621FD8845F9DAD05773D3739AE25899514ECF509CA07E68427E1942D59FBBD26,
		ram_block1a_2.operation_mode = "rom",
		ram_block1a_2.port_a_address_clear = "none",
		ram_block1a_2.port_a_address_width = 13,
		ram_block1a_2.port_a_data_out_clear = "none",
		ram_block1a_2.port_a_data_out_clock = "clock0",
		ram_block1a_2.port_a_data_width = 1,
		ram_block1a_2.port_a_first_address = 0,
		ram_block1a_2.port_a_first_bit_number = 2,
		ram_block1a_2.port_a_last_address = 8191,
		ram_block1a_2.port_a_logical_ram_depth = 19200,
		ram_block1a_2.port_a_logical_ram_width = 8,
		ram_block1a_2.ram_block_type = "AUTO",
		ram_block1a_2.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_3
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[0]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_3portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_3.clk0_core_clock_enable = "ena0",
		ram_block1a_3.clk0_input_clock_enable = "none",
		ram_block1a_3.clk0_output_clock_enable = "none",
		ram_block1a_3.connectivity_checking = "OFF",
		ram_block1a_3.init_file = "gatinho2_convertido.mif",
		ram_block1a_3.init_file_layout = "port_a",
		ram_block1a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_3.mem_init0 = 2048'h1FF9C36FFF9983D424DC30664E1F3FF0B8583D8017F61007FD11842F322CFF64B6043E322B001780079FA000FE03C31C9B14E0EF7E28F10CFC87F1E0003FF06115F3C144CABF072D7E4F60B412D8F2FC4501F1100233C77352087F808EFE0006984937E7F2587E000907DFB1E187DFDB4700CE63204A6787FE580FF004FCFFCF0FF7FFE5421F7FA1B0A3A9E7FE6C13CF0607FF9FC7B94D8DE03FDDA012111913C181B3CF6081CFFDC1CAD5CE31A32EE04B10296003A1FF1FE3C82FEF18883FEDB3DFD666EC0306F80BE206F3FFE08DFC16E037F1D3D7BFC57C00AB8EBFFFC2B01FF07E081E2AD43BE39FABC44184066E9FCBF2046EFFFC0E3837FAE7DF8383C1,
		ram_block1a_3.mem_init1 = 2048'hED3F6227278FFE78EFA05B7F01FFF9FE4FFF3C01E019CCD9338FD187BF00E63FE17FF3FA6F7FA7829B9D87A770E343131A3066FE611FCF001FFF8181FFFD0FC93F4C8BE5885446FE600BDB0081FFE383E3CC4B1201BF0EF860CE82FF4001DFC021FFF080C1DC6D4EDCEBBE56378049FEC04407000473FE0000DC6979008F48018FE03FFFFCC001C19C3000E00819021FA80F03730FF233F7F5C8E8FFE0981D1001001A858957A37985F01CEF78DF238FFE8784F180017A1A5667F839B0E01FFDEF33C000FFC19AFC0001C02F0CDFF01CB06037C971CCC08A7FE37FDE560F029EB367F1004040BFCE8EFDF883FE6100F05B8F87352819F041F998BFFC507E3DC0,
		ram_block1a_3.mem_init2 = 2048'h59F687FC79AF89980878FB70FC1E01AE0D024C20F32817FFE76C37F6187BF770FB3B91F01D52F6C1BF0617FD017D8F040333F7F83BFF0795087646112E0A1FFD0250FE1C73DFC3FBFFFEA00885A758BC817E9E7402F39F6C01C8E4083F8F85CA3F7A0FFB15E303F4013F218D2667B00D3FFC8531400C6962B3C683FE7FFD9B89E700204A9DF9FFFAE8676C6CBB038FEFF75E5B9D7BA23839F940C37F2419C61FFE3927FFFF8E208BDFFB9831809CE7BA60C5F1012568DA1C4FC3B0F5FF7BE62E037C07870B06E56D26B23D1D63F82CBF797FE64012B0786737AC60837A1C0705FBC77D4F39FFFECC3638489767BAC0AFE11E71E55DE06FFF08F7FC7F00980862,
		ram_block1a_3.mem_init3 = 2048'h3EE5FDB3003FDF8FD3750720D0DF6CF3100B6504DE7ACAE8C01FFFC47F78B0B7694D317D741ABB7CCD5E7466F0037F69F0C00717D1536BAE09B1CEC58B9DCFDEBE1CEF87DE34503A6EF9570AD2DDF66FFF0E220B3FF4CF47FAB7F151FCEDC7257AB732B8BDECB78A8FFC0C7FDFB1933D7F3CB92A380AF84F2216F00CE7F004FE7E18383470EFDAF169BAA13083CB094379FC01F0941AE03B791EC212C2234A9B423CE7AC647C0FC39E13A3D0B9C7DABF3E6E9D5803B0EF0C40180FD87D0121882DE7FCF52451088CB05716CD800C7C3F0E3AE08777FB99779643552DC3BFC8AD9C189F7BBBEBFE0305FB54EF5559C86CCC417FB0340021F9D71E1438FB7B3791,
		ram_block1a_3.operation_mode = "rom",
		ram_block1a_3.port_a_address_clear = "none",
		ram_block1a_3.port_a_address_width = 13,
		ram_block1a_3.port_a_data_out_clear = "none",
		ram_block1a_3.port_a_data_out_clock = "clock0",
		ram_block1a_3.port_a_data_width = 1,
		ram_block1a_3.port_a_first_address = 0,
		ram_block1a_3.port_a_first_bit_number = 3,
		ram_block1a_3.port_a_last_address = 8191,
		ram_block1a_3.port_a_logical_ram_depth = 19200,
		ram_block1a_3.port_a_logical_ram_width = 8,
		ram_block1a_3.ram_block_type = "AUTO",
		ram_block1a_3.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_4
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[0]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_4portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_4.clk0_core_clock_enable = "ena0",
		ram_block1a_4.clk0_input_clock_enable = "none",
		ram_block1a_4.clk0_output_clock_enable = "none",
		ram_block1a_4.connectivity_checking = "OFF",
		ram_block1a_4.init_file = "gatinho2_convertido.mif",
		ram_block1a_4.init_file_layout = "port_a",
		ram_block1a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_4.mem_init0 = 2048'h00063C9000660787E6DC0061C1FD00001BBFFD800009EFF802EE03CBCC1CFF6389F400302AFFFF8000005FFF01FC00E6FB6CFFE301E80100FDBFFFE000000F9EE20C00F96527F8E301E000B0FE37FFFC47000EEFF1CC00FD779F806381400000FFC4FF9FF27801FFF0F8007E0B180038C200CE60DFC11FFFFE78000FF803003FF6D8001CD61F7FA0CFE067FFFE6C0000F800003FF85EFFF3503FFDA0EFFFC4FFFF8000009F00001FFD0C17CEF1BFDEE0B7FFD8DFFFE000001C08201FE08FDFE3F3DFEE6613FCFED7FFE200000000800FE127D7F7F3D7C7C483FF7B85FFFFC20000000007E1A91001E39FC7C4807CFC607FFFF20461000003C7F80439FF83FFC1,
		ram_block1a_4.mem_init1 = 2048'h10459EC643BFFE07EFFFA300000006018000FFFE806AFC125DBFFF80FFFF0600E0000C0180807FFC9F98200FA6DFFCF0FFCF8780700000FFE0007FFE0002D019BC53741C7FAB8500600000FF7E001FFC1C33EC147660F0041F3140004000003FDE000FFF3E23F80015244002087F8000C04400FFFB8001FFFF23F404CB600003801FCC00FCC0003E63C0001FF7E6F80C40C00370C00FD808FBF8E0001F601C0FFEFFFEA464900378400FF0107FFF20000178040E7FFE850B5DA00038701FE000EFCFC000003E1803FFFE06A0AFB0001C701FC830FFE7C080001C8021A9F0075EF1100100203F0030B1FEF880019EFF0FA470039C1EC80040307E80008FFFFDC0,
		ram_block1a_4.mem_init2 = 2048'hF79BFFFF70600E58FF8707FFF9FFF8983CC1FC0D3F67FFFFF61C3855FF840FFFF3FFEC4A9A21F2072315FFFD0343F0A3FFCC0FFFEFFFF944D159C061E1ADFFFD024403078FE03FFFDFFFDC4FDDA8B884EE817E7402790B9AFFF01FFFBFFFFF2433FDFFC5F2E0FFF4013C21FCD9F84FFF7FFFFE522E3FFB5C11207FFE7FFE03F418FFDFFEFFFFFF2D04CCFC104DA07FEFF7FF83FC005DC7F9FEBFFF8EDAE43E003478DFFFFFFFC0E0000427F3FF03FFDA9E3E0F00E2A827FFCFFFC0F0008419EFFC03FFF86FF8836F0C3202FFE3FFCCD0008019DFFC4FFF9F9FADBF9F5A3C00FFFBFF85C0000001F3F9C7FF0FD45D006FA33E701F5DFF97A000000380FF67FF9F,
		ram_block1a_4.mem_init3 = 2048'h86E27E43FFFFD0700FCDE340C3C1BA89703D4350DFF94500FFFFFFC383CA2B1061CD258B3010192CDEBD8B80FFFF7F980F83BF0417DC921A38F19DAFF03C3818FFFFFFFFFE4E2CEB01FEC81E3EBE3EE01C3E2509FFFFFFFFF8CDDBCE03EFC7830DC1BE783D9C2C887FFFFFFFC141EA1580FFBF6647EB763F3E0EEB8C1FFFFFFE00EFE016C01F3A8F2650FF0FFFC7E2C787FFFFF064AD0017A901312DB077BF84BDE30ACC9BFFFFC01E0403D099C02580C66B0FB800700A8CBFFFFFC07C62019F95E0028BE46A0703F0371B4CFFF3FC3F0CB9C080F3F80741E6738BA03F9FF12CFFE79FFFFAFF9000FBF88A23EFE607F483DF8671FFFFDFFFF5FFD5703A78CF51,
		ram_block1a_4.operation_mode = "rom",
		ram_block1a_4.port_a_address_clear = "none",
		ram_block1a_4.port_a_address_width = 13,
		ram_block1a_4.port_a_data_out_clear = "none",
		ram_block1a_4.port_a_data_out_clock = "clock0",
		ram_block1a_4.port_a_data_width = 1,
		ram_block1a_4.port_a_first_address = 0,
		ram_block1a_4.port_a_first_bit_number = 4,
		ram_block1a_4.port_a_last_address = 8191,
		ram_block1a_4.port_a_logical_ram_depth = 19200,
		ram_block1a_4.port_a_logical_ram_width = 8,
		ram_block1a_4.ram_block_type = "AUTO",
		ram_block1a_4.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_5
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[0]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_5portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_5.clk0_core_clock_enable = "ena0",
		ram_block1a_5.clk0_input_clock_enable = "none",
		ram_block1a_5.clk0_output_clock_enable = "none",
		ram_block1a_5.connectivity_checking = "OFF",
		ram_block1a_5.init_file = "gatinho2_convertido.mif",
		ram_block1a_5.init_file_layout = "port_a",
		ram_block1a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_5.mem_init0 = 2048'hFFFFFFFFFFFFFFE7DF73FF9FC0030000F800027FFFFFFFFFFFFFFFF3FFB3009F800C0030D600007FFFFFFFFFFFFFFFF8E5B3001F001801000380001FFFFFFFFFFFFFFFFE73F0001F002000B001F00003B8FFFFFFFFFFFFFE99D8001F80C00000003C00000D87FFFFFFFFFFFFF4D80007C100CE60003F00000187FFFFFFFFFFFFF8180003CE1F7FA0001FE0000193FFFFFFFFFFFFFC1FFFFF303FFDA000003C00007FFFFFFFFFFFFFFF0BE831F1BFFEE0000007C0001FFFFFFFF7DFFFFF8BE01FF3DFFE6600000130001DFFFFFFFF7FFFFFE3E80FF3D7FFC40000047C00003DFFFFFFFFFFFFC7EFFFE39FFFC40003039E00000DFB9FFFFFFFFFCFFFFFFF83FFC1,
		ram_block1a_5.mem_init1 = 2048'hBFF601F87C3FFE0010000340FFFFFFFFFFFFFFFF0004FC1C7E3FFF80000006801FFFFFFFFFFFFFFF6067C00C277FFFF0000006808FFFFFFFFFFFFFFFFFFFE019C7FFFFFC000005009FFFFFFFFFFFFFFFFFFFF0107BDFFFFC00000200BFFFFFFFFFFFFFFFFFFFF00019DFFFFE000004003FBBFFFFFFFFFFFFFFFFF8000DDFFFFF80000400033FFFFFFFFFFFFFFFFFFC000EDFFC8FC000080000071FFFFFFFE3FFFFFFFC9A0ECFFC87C00010008000DFFFFFFFFBFFFFFFFE045EFFFFC7F000200010003FFFFFFFE7FFFFFFFF20EEEFFFE3F000400000003F7FFFFFFFFFFFFFFF9EF26FFEFFE00080008000077FFFFFFFFFFFFFFFDC3F67FFBFF0018000C000023F,
		ram_block1a_5.mem_init2 = 2048'hFFFE00005FE00FC9FFFFFFFFF9FFE073FAFFFC03FF60000003FC3FCDFFFFFFFFF3FFF03DF9BFF200DF080002FDFFFF9DFFFFFFFFEFFFF93471DFC0001F900002FD97FEFDFFFFFFFFDFFFFC3F9C4FF8841F80018BFD8207FAFFFFFFFFBFFFFF1F5E6FFFC00FE0000BFEC021F8FFFFFFFF7FFFFF0FAEBFFB400FE00001800003F4FFFFFFFEFFFFFF87FCFFFC0006600010080003F4FFFFFFF9FFFFFFD3FEFFFE0008380000000000E8FFFFFFF3FFFFFFE27EFFFF001BA80000300000E0FFFFFFEFFFFFFFFFBFF8FF6CF7B200001C000CD0FFFFFFDFFFFFFFFFE7AC3F809DBC0000040005E0FFFFFFFFFFFFFFFFA80000103CBE7000A20007A0FFFFFFFFFFFFFFFF,
		ram_block1a_5.mem_init3 = 2048'h86E05C03FFFFD000067CA30F33C431070FC180C0DFF86800FFFFFFC007799BC799CCC2070FE0D8ECDFFC2E00FFFF7FF802006D97EFDFF406070D1C7FFFFC2C18FFFFFFFFFD801893FFFFC0060100BE1FE3FE3709FFFFFFFFF981D5C3FFEFC79F00023E07C27C3688FFFFFFFFC001FBF1FFFFBF1E000C7E00C1FEF38CFFFFFFFE000FFFF17FFFFA7F001CFF00003FF347FFFFFFF004CFFFF0F6FFF0FF803BFF80001FF3CCFFFFFFC01E67FC30563FFC7FC673FFF8000FF3CCFFFFFFC07C2BFE7F8A1FFE7FE473FFFFF008E38CFFFFFC3F0C3D7F7FFC07FF3FF67B07CFFF8001ACFFFF9FFFFAFFFFFFF207FE1EFFF90006FFC007D0FFFFFFFFF5FFE4BFF587FF0F,
		ram_block1a_5.operation_mode = "rom",
		ram_block1a_5.port_a_address_clear = "none",
		ram_block1a_5.port_a_address_width = 13,
		ram_block1a_5.port_a_data_out_clear = "none",
		ram_block1a_5.port_a_data_out_clock = "clock0",
		ram_block1a_5.port_a_data_width = 1,
		ram_block1a_5.port_a_first_address = 0,
		ram_block1a_5.port_a_first_bit_number = 5,
		ram_block1a_5.port_a_last_address = 8191,
		ram_block1a_5.port_a_logical_ram_depth = 19200,
		ram_block1a_5.port_a_logical_ram_width = 8,
		ram_block1a_5.ram_block_type = "AUTO",
		ram_block1a_5.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_6
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[0]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_6portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_6.clk0_core_clock_enable = "ena0",
		ram_block1a_6.clk0_input_clock_enable = "none",
		ram_block1a_6.clk0_output_clock_enable = "none",
		ram_block1a_6.connectivity_checking = "OFF",
		ram_block1a_6.init_file = "gatinho2_convertido.mif",
		ram_block1a_6.init_file_layout = "port_a",
		ram_block1a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_6.mem_init0 = 2048'h0000000000000007FF8FFFFFC000FFFFF80000000000000000000003FFCFFFFF8003FFCFFE0000000000000000000000FFCFFFFF0007FEFFFF80000000000000000000007FCFFFFF001FFF4FFFF0000000000000000000001FE7FFFF803FFFFFFFFC0000000000000000000007E7FFFFC0FF319FFFFF0000000000000000000003E7FFFFC1E0805FFFFFE000000000000000000001E7FFFF0FC0025FFFFFFC00000000000000000001F000000E40011FFFFFFFC0000000000000000000F000000C200199FFFFFFF00000000000000000005800000C28003BFFFFFFFC0000000000000000003800001C60003BFFFFFFFE000000000000000000180000007C003E,
		ram_block1a_6.mem_init1 = 2048'h3FF7FFFF807FFE000000033F00000000000000000000FC1F807FFF800000067F00000000000000000000000FD83FFFF00000067F000000000000000000000019F83FFFFC000004FF0000000000000000000000107C3FFFFC000001FF0000000000000000000000001E3FFFFE000003FF0000000000000000000000000E3FFFFF800003FF0000000000000000000000000F3FFFFFC00007FF0000000000000000000000800F3FFFFFC0000FFF0000000000000000000000005F1FFFFFF0001FFF000000000000000000000020EF1FFFFFF0003FFF00000000000000000000001EF39FFFFFE0007FFF80000000000000000000001C3F9FFFFFF0007FFFC0000000,
		ram_block1a_6.mem_init2 = 2048'hFFFE0000601FF0380000000006000FFC070003FFFF6000000403C03C000000000C0007F907C00DFFFF0000000180007C00000000100002F30F603FFFFF800000001801FC00000000200001F82330077BFF8000000003FFF900000000400001F80170003FFFE00000000021FB000000008000007811C004BFFFE00000000003F3000000010000003C130003FFFFE00000000003F3000000060000001E110001FFFFF80000000000E70000000C00000002110000FFFC680000000000EF000000100000000030070093F872000000000CCF00000020000000003853C07FE07C0000000005DF00000000000000003FFFFFFFC07E70000000079F0000000000000000,
		ram_block1a_6.mem_init3 = 2048'h86E0640300002FFFFE839CB00C3C3FFF0001FFC0DFF874000000003FFE8784180633FFFF0000E7ECDFFC320000008007FFFFE19800200FFE0001E3FFFFFC32180000000003FFF97C00003FFE0000C1FFFFFE39090000000007FE2E3C0010387F0003C1FFFFFC3988000000003F7E040E000040FE000F81FFFFFEFC8C00000001FF70000F800005FF001F00FFFFFFFCC70000000FFB70000FC0000FFF803C007FFFFFFC4C0000003FE1B8000FE00003FFC67C0007FFFFFC4C0000003F83CC0000700001FFE47C00000FFFFC4C000003C0F3C18000080000FFF67CFFF0007FFE6C00006000050020000C0001FFFFFF0007003FF830000000000A001BC00E0000FF,
		ram_block1a_6.operation_mode = "rom",
		ram_block1a_6.port_a_address_clear = "none",
		ram_block1a_6.port_a_address_width = 13,
		ram_block1a_6.port_a_data_out_clear = "none",
		ram_block1a_6.port_a_data_out_clock = "clock0",
		ram_block1a_6.port_a_data_width = 1,
		ram_block1a_6.port_a_first_address = 0,
		ram_block1a_6.port_a_first_bit_number = 6,
		ram_block1a_6.port_a_last_address = 8191,
		ram_block1a_6.port_a_logical_ram_depth = 19200,
		ram_block1a_6.port_a_logical_ram_width = 8,
		ram_block1a_6.ram_block_type = "AUTO",
		ram_block1a_6.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_7
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[0]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_7portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_7.clk0_core_clock_enable = "ena0",
		ram_block1a_7.clk0_input_clock_enable = "none",
		ram_block1a_7.clk0_output_clock_enable = "none",
		ram_block1a_7.connectivity_checking = "OFF",
		ram_block1a_7.init_file = "gatinho2_convertido.mif",
		ram_block1a_7.init_file_layout = "port_a",
		ram_block1a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_7.mem_init0 = 2048'hFFFFFFFFFFFFFFF8000000003FFFFFFF07FFFFFFFFFFFFFFFFFFFFFC000000007FFFFFFF01FFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFF007FFFFFFFFFFFFFFFFFFFFF80000000FFFFFFFF000FFFFFFFFFFFFFFFFFFFFFE00000007FFFFFFF0003FFFFFFFFFFFFFFFFFFFFF80000003FFFFFFF0000FFFFFFFFFFFFFFFFFFFFFC0000003FFFFFFF00001FFFFFFFFFFFFFFFFFFFFE000000FFFFFFFF000003FFFFFFFFFFFFFFFFFFFE07FFFFFFFFFFFF0000003FFFFFFFFFFFFFFFFFFF07FFFFFFFFFFFF0000000FFFFFFFFFFFFFFFFFFF87FFFFFFFFFFFF00000003FFFFFFFFFFFFFFFFFFC7FFFFFFFFFFFF00000001FFFFFFFFFFFFFFFFFFE7FFFFFFFFFFFF,
		ram_block1a_7.mem_init1 = 2048'hC0080000000001FFFFFFFCFFFFFFFFFFFFFFFFFFFFFF03E00000007FFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFE600000003FFFFFBFFFFFFFFFFFFFFFFFFFFFFFFEF80000003FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE0000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000003FFFFFFFFFFFFFFFFFFFFFFFFFFFFF7FF00000003FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA00000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFDF100000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFE10C0000001FFFFFFF7FFFFFFFFFFFFFFFFFFFFFE3C00000000FFFFFFF3FFFFFFF,
		ram_block1a_7.mem_init2 = 2048'h0001FFFF80000007FFFFFFFFFFFFF00000000000009FFFFFF8000003FFFFFFFFFFFFF8060000000000FFFFFFFE000003FFFFFFFFFFFFFC0F80800000007FFFFFFFE00003FFFFFFFFFFFFFE07C0C00000007FFFFFFFFC0007FFFFFFFFFFFFFE07E0800000001FFFFFFFFFDE07FFFFFFFFFFFFFF87E0000000001FFFFFFFFFFC0FFFFFFFFFFFFFFFC3E0000000001FFFFFFFFFFC0FFFFFFFFFFFFFFFE1E00000000007FFFFFFFFFF1FFFFFFFFFFFFFFFFDE00000000017FFFFFFFFFF1FFFFFFFFFFFFFFFFFC0000000000DFFFFFFFFF33FFFFFFFFFFFFFFFFFC00000000003FFFFFFFFFA3FFFFFFFFFFFFFFFFFC000000000018FFFFFFFF87FFFFFFFFFFFFFFFFF,
		ram_block1a_7.mem_init3 = 2048'h791F83FCFFFFFFFFFF007FC00003C000FFFE003F200783FFFFFFFFFFFF007FE000000000FFFF00132003C1FFFFFFFFFFFF001E6000000001FFFE00000003C1E7FFFFFFFFFF00060000000001FFFF00000001C0F6FFFFFFFFFF00000000000000FFFC00000003C077FFFFFFFFFF80000000000001FFF0000000010073FFFFFFFFFF80000000000000FFE0000000000038FFFFFFFFFF800000000000007FC0000000000033FFFFFFFFFFC00000000000003980000000000033FFFFFFFFFFF00000000000001B80000000000033FFFFFFFFFFFE0000000000000980000000000013FFFFFFFFFFFFC000000000000000FFF80000000FFFFFFFFFFFFFE00000000000,
		ram_block1a_7.operation_mode = "rom",
		ram_block1a_7.port_a_address_clear = "none",
		ram_block1a_7.port_a_address_width = 13,
		ram_block1a_7.port_a_data_out_clear = "none",
		ram_block1a_7.port_a_data_out_clock = "clock0",
		ram_block1a_7.port_a_data_width = 1,
		ram_block1a_7.port_a_first_address = 0,
		ram_block1a_7.port_a_first_bit_number = 7,
		ram_block1a_7.port_a_last_address = 8191,
		ram_block1a_7.port_a_logical_ram_depth = 19200,
		ram_block1a_7.port_a_logical_ram_width = 8,
		ram_block1a_7.ram_block_type = "AUTO",
		ram_block1a_7.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_8
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[1]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_8portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_8.clk0_core_clock_enable = "ena0",
		ram_block1a_8.clk0_input_clock_enable = "none",
		ram_block1a_8.clk0_output_clock_enable = "none",
		ram_block1a_8.connectivity_checking = "OFF",
		ram_block1a_8.init_file = "gatinho2_convertido.mif",
		ram_block1a_8.init_file_layout = "port_a",
		ram_block1a_8.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_8.mem_init0 = 2048'h2A5D13E1B79B94D280F4767E366F86C6937409D3249C9D6C35B69247169E8834368A0E8761626415515910DDFA922DA6AE9A92D06E15B0E6C12101132E8A2897D9922A2DB2817261BB5CE12A4FC038E27AC8B5D25889122D0F7698C31AFD92D9244B45FE6C81BA2781E0425408687ACB9FC939329CA670066911D9B6427FD634C32C7C75312DD12C458C1783CD2F1798496F13993C44FB1FCE18057F2E6C45E625F1D10BF7C43867D6C76628D1EE630E99C2619510F30934C1D9F206AF20B943C2A52E4B121612590BB8ED7C3C61E29261C98298CB7E6A7ABCD9CE86ED5BB464DBCA28FCD3593F062D597DB8CC80AD2D12C0FBC5FD574840265B019779D5E325,
		ram_block1a_8.mem_init1 = 2048'h2699F6A82D88AC582DE3F1E033F0E10DA4BF606670CBE8FBC3B0BE325FAD5DF7A6802F29EC32078AD3B43F9CAF4A3BBB50A658E73DA29C05A82EAE72961B27ACA28EC3E043B9F0C867BB4E6826E0CA9F59CC8D996A1FF579B252C0A616FB3614251E9779A6B2F75AE3C3E51369C178CC2B17C568DE0F0D07EC45BEDCA85BA5F3D0275058DDDA15EB49BF8E76B1E3549365E088CF3ABF2140008481A1A99EEF895E10FF4E0CDCA65FE23EA4FE6A12A8939E5D81856AB475E3306E76D9C756F831D6F5892E79EFF3D5CDDDF22000A25A46C1DA7FA3FBAA5F078A9EF24665B8751ABF2CFA108C101AFD87500E5EC6EE3A812EC4B09B2109FD6F1836A0098993A8DC,
		ram_block1a_8.mem_init2 = 2048'h3FB46051FD282AF2BB000EF846BB824393BADFEC7E58939C2231B8E18A928424DA558040C6CA9FE78848A53596E921490ECF3C6C3B6FC2B1883F9F10C9F690CAF20C15658548C92DA8BBCC17B3321FF44D7AECE6C71373A3F536A593DC247498EC085FDDBDD5B9379D0A9A9061903815E44D9E4E2C694C75CE2DA699652DB785122EBC801ED85D81A4F98D709EB09FF9E572A2D55F30C6009DB7DDE618D8A238CDEEFA8FD3537CBB4A825A2898758E0E386131D316E70B4256A5FBB76E150C07135C565C621AE60CEF4124697B46B4E88D525C002BF1959DFE9C39CCF0FCAB3193BB2106A64BF0635429A8FC7A3F294E1CDACF72FF931F95FA4788011CE11C25,
		ram_block1a_8.mem_init3 = 2048'h2091A0BB6F9C6EF6A38D862A4E74BE897F1B0EEFFC220123A16E4E7D8EA9D62466C160FE0B2DE353C51D78DD46D85BB6D530E321EBEEBE5CEF8625CCE1CF38303BB14262384BBA4DABB7FD980ABEF9F2EF21BED92715D609759EEADBA6AB389511E4FC8D76887BC827026CE8384B7B2596E5A783EE4F4EBE6B4BE52D61E0E443838D7EF8021C0E3844120D5FA05717A91CD0C327656EB258AE3353D8949724153338D3D58D042B0C94D5512AF129799301F1F4756D7F4520C31973C54A74DC0C27CF1D04A4154A0144C6688293144D4CA4E4D1619A9BDFF2A23AAAE854308C6AECC8D4B4134574BE25BF5FDDB18E17E7F4C0482C171278630D593C78A5BF9FDA,
		ram_block1a_8.operation_mode = "rom",
		ram_block1a_8.port_a_address_clear = "none",
		ram_block1a_8.port_a_address_width = 13,
		ram_block1a_8.port_a_data_out_clear = "none",
		ram_block1a_8.port_a_data_out_clock = "clock0",
		ram_block1a_8.port_a_data_width = 1,
		ram_block1a_8.port_a_first_address = 8192,
		ram_block1a_8.port_a_first_bit_number = 0,
		ram_block1a_8.port_a_last_address = 16383,
		ram_block1a_8.port_a_logical_ram_depth = 19200,
		ram_block1a_8.port_a_logical_ram_width = 8,
		ram_block1a_8.ram_block_type = "AUTO",
		ram_block1a_8.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_9
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[1]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_9portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_9.clk0_core_clock_enable = "ena0",
		ram_block1a_9.clk0_input_clock_enable = "none",
		ram_block1a_9.clk0_output_clock_enable = "none",
		ram_block1a_9.connectivity_checking = "OFF",
		ram_block1a_9.init_file = "gatinho2_convertido.mif",
		ram_block1a_9.init_file_layout = "port_a",
		ram_block1a_9.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_9.mem_init0 = 2048'hB8F62D18F4E16376A03D000F8B12040F020457DF523986E77B6C9F7B860FB59B62FF73A095DE57F6D506C1F93DBE33AD072F20C31EBCC67C148E7F0CA93263462DA41663CDCD1594F307E752DFD58CB56A8F5AE46CCF6EFF595287DB4E2C2FDD01410CAF0BE7ECDFFD03A14AE1514DC4019631F84725DDFF3A85CB49AB877E961EA724BEFAA1DDC1AECEDFE59028B33D6AA6CF8E7B388DAF6B8980358DD61C16CD27EF94B5D42196CFDF51F07B757814C2D7AC96F6E430265579AFBD249922BC9C164F203E9BAB19DBD3BE831598B439F7A38A79CA9540C65C9070B8090029F9734AB89E99F2B34B86048C7FDD1B6924B2EB7FD2E5C7D5C4382E6C697423065C,
		ram_block1a_9.mem_init1 = 2048'hCFEAA43FEDB72068B95481E9494F24042E591E6961B5A7914086D614DB2B75926D0728AD0E73E617B9AA4C5AC107A3AE2B81F9ECB5D70460DE427BCC21C10F60D447FF10F370593C1175FCA8E895395FA935A17D899A5104F716EB298C685C14A50AC89F3C7183800E3E7EB44653C10A68EAB26BF7E19CA75F08961393C067BEBF3E144D4F88B78FC0FD27F7B79321411804D603489FD6ADD54757E3D2ECE10FBD9688527EA8E65107F62BE64C13ED4334B3DB5C6310D138AB715762D8466ABF6FF3AA8EF5E03E63D5081C95F3D2951BC34F96D525F32CEAC24986AB2DD9F978E595B7954110F6B9C439BADE5CA4C4A06BACDC1D35A9EC2BE1D3FF4037703FE7,
		ram_block1a_9.mem_init2 = 2048'h6D1206DF6FA67422654EEE7EDF753884CDCBBFC7ECA62ABACA300E15099B445D88A255836571FFDE9D46ECCA3741B292D4BEEF38B0905ABB0D703FF4FC86652C859ACFBDFA538B19A85FBA58010EFF8BC8AED3D01EEED00BD63FCF1CE0BCB34826D5FFAE79DF3FAE539B454B87E73125D9DEFE31631B3FCC41FE9D6C531C8979FD7C27CE6F808AF0E7665E0F97796C061A3CE274AAB41A44EF3BD890953C6D898789EFB8B426B73AD9593CB323A07884CCE0FF605BC3CBE49EAD4FC9FA5EEA7A306E93102781A9D429C3B503D906809D27F7B9170ACF8EA0F558F6EDA135A3E018EFAFACC73E64FC9F1DDE675BECC7FBBC5C241B0099E7AB37500F8902C0D3D3,
		ram_block1a_9.mem_init3 = 2048'hE57922790CFAC61773C7EE164D5C103984C548ECC50A11F41F16C51A9D3DCB06A43FC7790D2566034E4F70AB606EB650CF5509CA67025445F20D4038E4C307327378E8CEF872F23998B8C1468A17DF5AD1A6C0E95C6A7D9A226579000439997D4D27986569A7B935CAA62D5C35568A0EC57718063F5CDDAB756B5534D0F6F8820A2B1D466641B1C5CBA2DB94DC92D493929E82F20599B815C0F6BDEA3DA36D83BED10227C5E8B793DB31B23F31BBFFD61EB34E8B13751D5F2DBCFC1BC728EE38F6DFFFCEF8A1BA0A8DA7805C30A6D960637E44F2618B3FD2612EA06BD15100A0FBDF6BDA3977E3CCDF2A7FF73D5E1EEA88428E255FA62583D5A84A52E8C77FE5,
		ram_block1a_9.operation_mode = "rom",
		ram_block1a_9.port_a_address_clear = "none",
		ram_block1a_9.port_a_address_width = 13,
		ram_block1a_9.port_a_data_out_clear = "none",
		ram_block1a_9.port_a_data_out_clock = "clock0",
		ram_block1a_9.port_a_data_width = 1,
		ram_block1a_9.port_a_first_address = 8192,
		ram_block1a_9.port_a_first_bit_number = 1,
		ram_block1a_9.port_a_last_address = 16383,
		ram_block1a_9.port_a_logical_ram_depth = 19200,
		ram_block1a_9.port_a_logical_ram_width = 8,
		ram_block1a_9.ram_block_type = "AUTO",
		ram_block1a_9.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_10
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[1]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_10portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_10.clk0_core_clock_enable = "ena0",
		ram_block1a_10.clk0_input_clock_enable = "none",
		ram_block1a_10.clk0_output_clock_enable = "none",
		ram_block1a_10.connectivity_checking = "OFF",
		ram_block1a_10.init_file = "gatinho2_convertido.mif",
		ram_block1a_10.init_file_layout = "port_a",
		ram_block1a_10.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_10.mem_init0 = 2048'h201122296BEF241B722FB4D7F5A7F42B248A20F5B6233FED9778546F9CA95593109D60592402B075608627400E4F02121B58DA1A71CC5C91A58823E1644258AB0AE57F130DB227D21C49447C540D6BE87A8297C2C2547C1AC22C5E7C2CF8D4BF9588574F9701482177F676D422A6AFC4B38CA7421DC102AF361EF05559AF0B3229019B6DB5B804856C2F0EB6D190765CDF283F75E22328F2C11E5E9E7F65E4D2E533C1B3E3E9C8D7DC33EE232BB7C9D6A192B710B6E0B3BE9961E124CC291A58190B68B451BB035EABD53DFE74F4365CC1C77D4D32D2F7503B36411FFA37767EAE4695E8EC13F51C1DD6C9DE242027FEF8D4D8B0A53CC5A1C3EBFEE2122CA7F8,
		ram_block1a_10.mem_init1 = 2048'hA3ED4E1B4FB507605D34C21A6B529110D647D581ECD02CF06D1F9B8D1C00EBF13104CAC638961AEB4F45C650CF7C331B17F9EF04567ECC2A5EB2F58E9469278C163AB99A02F87625676B99D8756E0A1D4EFFE0D1C6CB6CB52F44B00121830B4C1B1759B4814C8FFE0F42F4C24F345C82FF579504771D849FCF36450EAC232FAFDD67BBAEC6EEB8607EEFBFC6358573CC93B509F88008C976B73161C99E7BD927ED87ED76093311C8C767A3B872FED360FC38607126A4B83926551E009D16CE7070BC2FA5958600E2BC9C342DD4DF2C6B82070F64701057BC3D0141E42B4C1FF3606AE3974EEE236AF87CD4AA44E32C4E36A6CEB21FCF93BE27ADA3AD138F50A5,
		ram_block1a_10.mem_init2 = 2048'h4E2741441CC6F50A4E0A4F3B8FF55A80E49C7FF3B0D90E9FC421BEB701A7B13FFD058CCC4E74FFE02E672A6162EC653FFFD63031F963BD5FAD4DFFDD9176AEAD0818B86A81DC3EC18B34E985B7BABFD16D0CB4CBAD2276A83DF859C44820DDF41DC67FE0A53C7D50FF19C838039E5CA533D4E856B5341FA7637201A9A41CF76218B0542F15A9D91093FABFDAE85946782715DCBE31370C4118AC76D5A567FE8568B5A5F81D9678D573F6D37F3E446560AE68C0A50A29841126EA1527C1894125569239204DD9704412DB75577B616E0B21F6425EA6183074A12EC8359D7075F0BE90B820E70B0556EA11F9339050AF556454ED369136D8B881B5C57B1DD8D299,
		ram_block1a_10.mem_init3 = 2048'h48EA4CD0935627FC29157A48BA0DF009569929465DAE9802E0E026CBFBDA0B218132407759B9019F5076479913081E04536D69335A65D393AB1D670443144308C8E31D33E13D20459E85EA11A312FC12000800E2575E321E53BFE603C9FB8612D6183466ECD239E0F1D1483AC8A22005F051FFE06CB50D111DF07EE977AC05944E49D2B0851EFFE1ACF7F0520C94EF960DA87BBB7BBFA60BC7797FEB9E72A67A3CD6D211DA35FF90C44B1D7DBF4EFFF4DF014A11D2C01D139848C144836C90308E82FFE43F0118A46FF2A45A41A00319749A190F5B627FF63C30705F005F449092E06469AAB31FE51AE8BFFDA1EDA43A1B86F149968BAAE5B4D1D14001227FEC,
		ram_block1a_10.operation_mode = "rom",
		ram_block1a_10.port_a_address_clear = "none",
		ram_block1a_10.port_a_address_width = 13,
		ram_block1a_10.port_a_data_out_clear = "none",
		ram_block1a_10.port_a_data_out_clock = "clock0",
		ram_block1a_10.port_a_data_width = 1,
		ram_block1a_10.port_a_first_address = 8192,
		ram_block1a_10.port_a_first_bit_number = 2,
		ram_block1a_10.port_a_last_address = 16383,
		ram_block1a_10.port_a_logical_ram_depth = 19200,
		ram_block1a_10.port_a_logical_ram_width = 8,
		ram_block1a_10.ram_block_type = "AUTO",
		ram_block1a_10.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_11
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[1]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_11portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_11.clk0_core_clock_enable = "ena0",
		ram_block1a_11.clk0_input_clock_enable = "none",
		ram_block1a_11.clk0_output_clock_enable = "none",
		ram_block1a_11.connectivity_checking = "OFF",
		ram_block1a_11.init_file = "gatinho2_convertido.mif",
		ram_block1a_11.init_file_layout = "port_a",
		ram_block1a_11.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_11.mem_init0 = 2048'hD8110019A42CD37BAACFF87974223A9C0B323B32CE00001DE34DFF53B6D5BC159489F1AC02270E94FC06C72473AD6703AE1C4740CF85C3AB84DF9E10EC022F890D2E6F184F31B192B4C6AAD5DC22EC299A8E0BC1C085F06085A8AEA26B32A10A6DCBC60EFFFF0700F741FD24363DA3792C79D0681236930ACCFFC1A0FC0CF9F73F5D5A572EF90BDDD82D2B832E67C0E03611F1C071277EC919CFA19AC3253AB31ADC097F1D1FFCACD36694998B8A69C30BB0DF078910C81E919E8FE3FBFBB5C8C57E9AA9DB887397842C3C01057FC2683CD07988BFB97CB148FF95EF078F00001A7D3B1CD285F60AC33D4940EC9607D7073FC70C2679179DC0F36EEB485CFE22,
		ram_block1a_11.mem_init1 = 2048'h7DBC744C229DC7A7F311B407724BF58306419B8EF934B6C99C2F6C3DCAEE160EB60517B938FE3D8FF86A9230AFAE1D87062DEB72945EC1661EFE1F8EF422B49369EE908EAAC9ACC6456751F5017C461FAD47DD4007D383F215340FB1EE7B3A45019E245160CA41D7A9E30CF05628204B3632741D771FB8E1C371A80D05C3DF9F55EFD5AD99B9B3507EFF9858369C0EFA1BC9CC03F2E1B09A3AF302C99E780691E9899EE5074401B089ED118AC9F01D33FC3000C12537A21D2CCC820E15CECA9E438F9E58F586002098C0497AC65D0309184E1466E408C3BDF9C100234BB49A4A5C1EB1D2582D7AD68FD44AB9BCE300205C4F2997A2AD6419415FDE6E9828ED22,
		ram_block1a_11.mem_init2 = 2048'h703DAA93E67604E6B7B4EA3E5004918726DCFFEEC0E9B144F7418E73EF355BEDF3F3034F1BB57FE2CF905EFCF713E77A982A7A1287E8C8FA230A7FFF1E44B2C68DE8FF16215F1DCA97E8FBC26106FFFC719C52D2AB70918675442647C7D8EFC3194ABFD2C7197BC37A64A7560563D53DF83CC6480626BFCD8B1AFD2C22284175EB4DDCB14C69E67C8726DFB72D83EF0CA0C550B5DD4E0512A05FEED1B76CBF525228F2342EFCC0D199F95EF9381CF1E0DFE3AF55AED2EB07369227EC140F15857016EA80685CCD66B22A79597D2E39FE59F551882207F804F1AAEE3F1DDE15CF37A5E0DFF2FD213900006087F47A4F8DCE0D8EAF8F230044A5F43AB4EFC09E1E,
		ram_block1a_11.mem_init3 = 2048'h908B8FE25FB98753DF9F69A66C770FF398E1B18B4DCD1FFB03C1A5EB67E700A6C7133F8591C1B9EE5F987E7D8556D742AF7552326551CFE533E1B9F95C187CFC85ABB9A795340FA08B91E7E533EF21FB1C30FF1C6776F4FAB7B4C7C3F1A17FE567FD219A78E3C61EFDD6F5C43FFA0484B40B7FF54FF96E207DC3801871D6EA2627BAA1711EE67FF4CFFB9D90F4E70072019C1E4D9F3FE9E16D26FFFEDFFBB67C2D272DF0C00552E63B0C300FDA87FFE29FFAECE130C1E2F1004AFA4C381F20CDA34BFFF2BFFB5CA8FE13C3B8818000F15BF982BC652CFFE0BFC5B209445F83760F2A160C6076988A70B47FED3E0A0967139900E574FCFDE1D938DBA56EA2FFFD,
		ram_block1a_11.operation_mode = "rom",
		ram_block1a_11.port_a_address_clear = "none",
		ram_block1a_11.port_a_address_width = 13,
		ram_block1a_11.port_a_data_out_clear = "none",
		ram_block1a_11.port_a_data_out_clock = "clock0",
		ram_block1a_11.port_a_data_width = 1,
		ram_block1a_11.port_a_first_address = 8192,
		ram_block1a_11.port_a_first_bit_number = 3,
		ram_block1a_11.port_a_last_address = 16383,
		ram_block1a_11.port_a_logical_ram_depth = 19200,
		ram_block1a_11.port_a_logical_ram_width = 8,
		ram_block1a_11.ram_block_type = "AUTO",
		ram_block1a_11.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_12
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[1]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_12portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_12.clk0_core_clock_enable = "ena0",
		ram_block1a_12.clk0_input_clock_enable = "none",
		ram_block1a_12.clk0_output_clock_enable = "none",
		ram_block1a_12.connectivity_checking = "OFF",
		ram_block1a_12.init_file = "gatinho2_convertido.mif",
		ram_block1a_12.init_file_layout = "port_a",
		ram_block1a_12.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_12.mem_init0 = 2048'hF8110006252B3C3D6D8A007B33DE41440C91CA0FFE00000206DB211C599FFBD37F7980E40771FF6BFC0607038400E89831043FA6207A2C6784B7FFFFEC020F88F69AF5607313BC0E73C03033DC3AEFDFFA8E03C03EB8FA80FC658E3EE73E2779FDD6C7F1FFFF0000083FF004D1A4647C9FF85779EFF513F1FFFFC0000173FEF7D70D3B7C9F8957DC07E30BF9FFFFF000077FF2FD98C7A5F8B9C1387E04E2A0ADFFFFF900007FF4C338E6C1B89B8056368470F01F7FF0F8016AFC744018199FF9BDF8A9DD547BD41F7FFC3C00F10667E81AA84BFB9E3E5DF3440E320FFFFF00000D899C48D9F1A179BF52D4C7D00F1007FFFFC0002AE08B91D00F9899384E42EC,
		ram_block1a_12.mem_init1 = 2048'h01801518DC2207E00F1127FEFC420DC30641A0700601E2708043FFFDC61083FE3804FF4638FE0070078D5260AFA7F87F0E1F3A6AE841C0B01EFE00710BBA5AD27F6D607EE606F251B960D61401FC01E0127EE487F8DC000FF30B3695D004F987019E03EE1EAE0F07D1FC030FB17FA4DFB00DF4C7771F837E3DB487A7F1FC007C331FD4B71C47B3307EFF803FC91B746FE3FE33FC49E020743A0F03B89E78007E10159D0FF77FFFFFA5E39118530E2108FC30003EDA9C93C2CE3DFE0E4DC16D7D6E7F7005F586001F62299C96E6DFFF08B831A1280BB83842F9C1001F91D1FD8BB71F5311381C5C4677CC3D66FCE3001F85A1D1A445AEC43B20FFEED462681E1F,
		ram_block1a_12.mem_init2 = 2048'h7FC63393C606041EF83A4041B00BE07FFF1FFFF4FF0EC30706818E0FF034D733F00FF733FF32FFF4F01D8E0E0601E706E039CB4F80073005DF86FFE9E07F3E086C08FF0E3E5F41108007043FFECE7FE981EF6EDC4880EF9E7A7C786FC007003FF2267FEB06DE47FC9981C0CE067EDE15F80301BFF8027FE60C9CFDD3C1C0812C0C7CF5587C16018F79E1BFCC321DEFF3C1F9909C1E7EF616B800012E48639FBC6431FFC3C1F880C41DFF0D7B38130E1F00679E29C263F7F8C97C47E6180F2A237011047FA01BC00F224B8EA086EF4FFB11F73096220001FB310933B1DD9FFA00CFBECFFCFBF915E8080007F81001417E7F93F0207F3F6FFDB9F401A70FC0A1E0,
		ram_block1a_12.mem_init3 = 2048'hFF0BF003D7FF896C006097EF91CEFFFDE0FE3E0FB20FE003E7DFCBF40000FFC708CAFFF9E1FE3E0FA01F8001FB30FBDF008ABFD398A83FF9C3FE3E09A01F8000FB53C13D02C3FFE164781FF9C3FC3E1BE03F00007DF6A75E08433FC20A54FFF987FE3E1F80FC0000FF59B9840805FC8541F4FFF98FFE703F85FC00067056F8A610047FF1C4F1FFF90FFCE1EF04F8000C00EA5E5500305FF99071FFF31FFCC7802DF8000EC081E27B0003CFFF0501FFFB1FFC8F01033E000E005D16098003DF3FDC89FFFB3FFD9F4FD80C000701A7E2A7C387FF7F7E4DFFFB3FF933770850000F03F272E52389E77FFF05FFF63FF309FF0380001D88E44D86F187A4FFFF3FFFF6,
		ram_block1a_12.operation_mode = "rom",
		ram_block1a_12.port_a_address_clear = "none",
		ram_block1a_12.port_a_address_width = 13,
		ram_block1a_12.port_a_data_out_clear = "none",
		ram_block1a_12.port_a_data_out_clock = "clock0",
		ram_block1a_12.port_a_data_width = 1,
		ram_block1a_12.port_a_first_address = 8192,
		ram_block1a_12.port_a_first_bit_number = 4,
		ram_block1a_12.port_a_last_address = 16383,
		ram_block1a_12.port_a_logical_ram_depth = 19200,
		ram_block1a_12.port_a_logical_ram_width = 8,
		ram_block1a_12.ram_block_type = "AUTO",
		ram_block1a_12.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_13
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[1]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_13portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_13.clk0_core_clock_enable = "ena0",
		ram_block1a_13.clk0_input_clock_enable = "none",
		ram_block1a_13.clk0_output_clock_enable = "none",
		ram_block1a_13.connectivity_checking = "OFF",
		ram_block1a_13.init_file = "gatinho2_convertido.mif",
		ram_block1a_13.init_file_layout = "port_a",
		ram_block1a_13.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_13.mem_init0 = 2048'hF81100002717FC402F8E0078F0018043F0D7FBFFFE00000007A7FA601F9C0010F00600E3F843FFFFFC060700067FF2E03F03FFC1E0000FE07B25FFFFEC020F88077DFB807F0EB821F03FCFF023D3EFFFFA8E03C0027FF900FC187441E0C1C8F8022AC7FFFFFF000000FFFC04F05C1A83800798F8000193FFFFFFC00000FFF6F7F0ED06838076985C00150BFFFFFFF00006FFF8FDF7F66007863E3FFE001AE0BFFFFFF90000FFFBFFF7F7F047847F9FF6000DF01FFFF0F800057FFB7FF789BF07820737FC5005501FFFFC3C000F3BDA77F748140781C063F04000A00FFFFF0000071C011736399A8780EF63C0C0005807FFFFC000266CC39E301FED0707B081E0,
		ram_block1a_13.mem_init1 = 2048'h01807A8FFFC007E000EE380100420208064180000001D86FFF83FFFDC1FF04014004000438FE0000000DE86E5027FFFF01FE1F9D80403FDC1EFE0000003AE0DF806FFFFEE1FF137181602FFB01FC0000007FE2DE00DFFFFFF0FFD0D3400007C6019E000000EE11DC01FFFFFFF0FFD36970000BC7771F800001F4099801FFFFFFF0FFEBB48C004CF07EFF80000198883003FFFFFFC7E00F01C200FC789E78000001926030077FFFFF9DE02E816301FEF8FC30000003B36CFC0E7DFE0E3DC070F20B80FFFDF586000003E7EEF906DFFF08780038E17287FFFFF9C10000020FC5F4071FF310F8039FC1F943FFFEFCE3000006DFFDD807AFC438E0000EC3FCA7FFFF,
		ram_block1a_13.mem_init2 = 2048'h7FF83C6C060604010037877FF0000000001DFFF8FFF0FCF806018E000033EFBFF00007000031FFF8FFE1F1F00601E701003BEBAF800000000001FFF1FF87C1F00C08FF01C05D01D0800000000001FFF1FE0F81200800FF81807D004BC00000000001FFF3F81F80001801FFC1F87EA405F80000000001FFF7F01F02000000FEE3F07C45C07C00000001E07FEFC01E10000001EF73E07E3BD6B800000000607FDF803E00000000FF33E1FF33873810000000607FBE027C00000000781DE00F11DF7010000020183E782274000000107006E1F7086E22000000310803C9DDE000000040F00203F909180800000010004E87FFE0002000C0700341F4062C0FC08000,
		ram_block1a_13.mem_init3 = 2048'hFFF40003CFFF9F7F00000010203DFFFE00FFC00FFFF00003EFC01FFF000000181039FFFE01FFC00FFFE00001F70F0FDF0000000C101BFFFE03FFC009FFE00000FF0C013D0000001E080BFFFE03FFC01BFFC000007F09372E0000003C0C0BFFFE07FFC01FFF000000FD2039B40800037A060BFFFE0FFF803FFA0000007126E4960000000E070BFFFE0FFF01FFFB000000008DF94500300006018BFFFC1FFF07FFD2000000C00601730000000001FBFFFC1FFF0FFEFC000000003F118D8000000000F3FFFC3FFE1FF020000000019C01DFC38000008077FFFC3FFE3380F050000003E871F923800000003FFFF83FFC0E00E380000200EF6187F1800000003DFFF8,
		ram_block1a_13.operation_mode = "rom",
		ram_block1a_13.port_a_address_clear = "none",
		ram_block1a_13.port_a_address_width = 13,
		ram_block1a_13.port_a_data_out_clear = "none",
		ram_block1a_13.port_a_data_out_clock = "clock0",
		ram_block1a_13.port_a_data_width = 1,
		ram_block1a_13.port_a_first_address = 8192,
		ram_block1a_13.port_a_first_bit_number = 5,
		ram_block1a_13.port_a_last_address = 16383,
		ram_block1a_13.port_a_logical_ram_depth = 19200,
		ram_block1a_13.port_a_logical_ram_width = 8,
		ram_block1a_13.ram_block_type = "AUTO",
		ram_block1a_13.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_14
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[1]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_14portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_14.clk0_core_clock_enable = "ena0",
		ram_block1a_14.clk0_input_clock_enable = "none",
		ram_block1a_14.clk0_output_clock_enable = "none",
		ram_block1a_14.connectivity_checking = "OFF",
		ram_block1a_14.init_file = "gatinho2_convertido.mif",
		ram_block1a_14.init_file_layout = "port_a",
		ram_block1a_14.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_14.mem_init0 = 2048'h07EEFFFFD97FF87FD071FF87F000004000EFFBFF01FFFFFFFB7FFC7FE063FFEFF00000E0007FFFFF03F9F8FFFAFFFCFFC0FFFFFFE0000FE0003BFFFF13FDF077FAFFFDFF80FE403FF0000FF0001DEFFF0571FC3FFDFFFDFF03FBF87FE0000FF8000DC7FF0000FFFFFFFFF9FB0FF3FCFF80001FF8000693FF00003FFFFFFFFB080FE2FCFF80001FDC00068BFF00000FFFF9FFFD020FE81EFF80003FFE000360BF000006FFFFFFFD000FE8CEFF80001FF60001301F000F07FFFEFFFD800F8631FF80003FFC5001B01F0003C3FFFF7C3C800FC7D1FF80007FF04000D00F0000FFFFFFC1BE600FF663FF80007FC0C000680700003FFFDE9FBC200FF80FFF0000FFE0,
		ram_block1a_14.mem_init1 = 2048'hFE7F800FFFFFF81FFFFFC000FFBDFFF8F9BE7FFFFFFE006FFFFC00023FFFF800FFFBFFFCC701FFFFFFF2006EFFD80000FFFFFC007FBFFFFCE101FFFFFFC500DFFF9000011FFFF38E7E9FFFFFFE03FFFFFF8000DFFF2000000FFFF0EFBFFFFFC7FE61FFFFFF11E1DFFE0000000FFFF0774FFFFFC788E07FFFFE0BF19FFE0000000FFFFFBB93FFFFF081007FFFFE67F03FFC0000003FE03F07FDFFFFF86187FFFFFE6FF03FF88000007DE03F837CFFFFF803CFFFFFFC4FF0FFF18201F1FDC07FF30C7FFFFD0A79FFFFFC1FF0FFF92000F7F8003FE1037FFFFF063EFFFFFC3FF9FFF8E00CEFF8001FC001BFFFFE031CFFFFF8BFF9FFF8503BC7E0000EC000DFFFFF,
		ram_block1a_14.mem_init2 = 2048'h80003FFFF9F9FBFFFFCFFF800FFFFFFFFFE3FFFF0000FFFFF9FE71FFFFCFFFC00FFFF8FFFFCFFFFF0001FFFFF9FE18FFFFC7FBF07FFFFFFFFFFFFFFE0007FFFFF3F700FFFFA301DF7FFFFFFFFFFFFFFE000FFFFFF7FF007FFF83004F3FFFFFFFFFFFFFFC001FFFFFE7FE003FFF81840507FFFFFFFFFFFFF8001FFFFFFFFF001FFF83C5C083FFFFFFFE1FFFF0001FFFFFFFFE000FFF81FFD647FFFFFFFF9FFFE0003FFFFFFFFF000FFE00FFFFC7EFFFFFFF9FFFC0027FFFFFFFFF8003FFF0FFFF8FEFFFFFDFE7FF80227FFFFFFFFF8001FE08FFFEDDFFFFFFCEF7FC01DDFFFFFFFFFF0001FC06FEF8F7FFFFFFEFFFB007FFFFFFDFFFFF8000FE0BFFDCF03F7FFF,
		ram_block1a_14.mem_init3 = 2048'hFFFFFFFC3FFF9080FFFFFFFFC003FFFFFF00000FFFFFFFFC1FC01000FFFFFFFFE007FFFFFE00000FFFFFFFFE0F001020FFFFFFFFE007FFFFFC000009FFFFFFFF07000EC2FFFFFFFFF007FFFFFC00001BFFFFFFFF830038F1FFFFFFFFF007FFFFF800001FFFFFFFFF03003E7BF7FFFFFFF807FFFFF000003FFFFFFFFF8F06FF79FFFFFFFFF807FFFFF00001FFFFFFFFFFFF8FE7BAFFCFFFFFFE07FFFFE00007FFFFFFFFFF3F87FF8CFFFFFFFFFE07FFFFE0000FFFFFFFFFFFFFFFEFF27FFFFFFFFF07FFFFC0001FFFFFFFFFFFFE7FFFF83C7FFFFFFF83FFFFC00033FFFFAFFFFFFC1B8FFEDC7FFFFFFFC3FFFFC0000FFFFC7FFFFFFF1F9E780E7FFFFFFFC3FFFF,
		ram_block1a_14.operation_mode = "rom",
		ram_block1a_14.port_a_address_clear = "none",
		ram_block1a_14.port_a_address_width = 13,
		ram_block1a_14.port_a_data_out_clear = "none",
		ram_block1a_14.port_a_data_out_clock = "clock0",
		ram_block1a_14.port_a_data_width = 1,
		ram_block1a_14.port_a_first_address = 8192,
		ram_block1a_14.port_a_first_bit_number = 6,
		ram_block1a_14.port_a_last_address = 16383,
		ram_block1a_14.port_a_logical_ram_depth = 19200,
		ram_block1a_14.port_a_logical_ram_width = 8,
		ram_block1a_14.ram_block_type = "AUTO",
		ram_block1a_14.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_15
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[1]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_15portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_15.clk0_core_clock_enable = "ena0",
		ram_block1a_15.clk0_input_clock_enable = "none",
		ram_block1a_15.clk0_output_clock_enable = "none",
		ram_block1a_15.connectivity_checking = "OFF",
		ram_block1a_15.init_file = "gatinho2_convertido.mif",
		ram_block1a_15.init_file_layout = "port_a",
		ram_block1a_15.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_15.mem_init0 = 2048'hFFFFFFFFFEFFFF80000000000FFFFFBFFF000400FFFFFFFFFCFFFF80000000000FFFFF1FFF800000FFFFFFFFFDFFFF00000000001FFFF01FFFC00000FFFFFFFFFDFFFE000001FFC00FFFF00FFFE01000FFFFFFFFFFFFFE000007FF801FFFF007FFF03800FFFFFFFFFFFFFE00000FFF007FFFE007FFF86C00FFFFFFFFFFFFFC00001FFF007FFFE023FFF87400FFFFFFFFFFFFFE00001FFF007FFFC001FFFC1F40FFFFFFFFFFFFFE00001F3F007FFFE009FFFE0FE0FFFFFFFFFFFFFE00007FCE007FFFC003AFFE0FE0FFFFFFFFFEFFFF00003FEE007FFF800FBFFF0FF0FFFFFFFFFE3E7F80000FFC007FFF803F3FFF87F8FFFFFFFFFF007FC00007F000FFFF001F,
		ram_block1a_15.mem_init1 = 2048'hFFFFFFF0000000000000000000000007FFFFFFFFFFFFFF90000000000000000000000003FFFFFFFFFFFFFF91000000000000000000000003FFFFFFFFFFFFFF200000000000000C0000000000FFFFFFFFFFFFFF200000000000000F0000000038FFFFFFFFFFFFFE200000000000000F8080000038FFFFFFFFFFFFFE6000000000000000406000000FFFFFFFFFFFFFFFC000000000001FC0F800000007FFFFFFFFFFFFFFC000000000021FC07C80000007FFFFFFFFFFFFFF0000000000023F800CF0000002FFFFFFFFFFFFFF000000000007FFC01EFC000000FFFFFFFFFFFFFE000000000007FFE03FFE000001FFFFFFFFFF7FFE00000000001FFFF13FFF000000,
		ram_block1a_15.mem_init2 = 2048'hFFFFC0000000000000000000FFFFFFFFFFFFFFFFFFFF00000000000000000000FFFFFFFFFFFFFFFFFFFE00000000000000000400FFFFFFFFFFFFFFFFFFF80000000000000000FE20FFFFFFFFFFFFFFFFFFF00000000000000000FFB0FFFFFFFFFFFFFFFFFFE000000000000000007BFAFFFFFFFFFFFFFFFFFFE000000000000000003A3FFFFFFFFFFFFFFFFFFFE000000000000000000029FFFFFFFFFFFFFFFFFFC000000000000000000000FFFFFFFFFFFFFFFFFD8000000000000000000000FFFFFFFFFFFFFFFFDD8000000000000000000001FFFFFFFFFFFFFFFE220000000000000000000007FFFFFFFFFFFFFFF8000000000000000000000003FFFFFFFF,
		ram_block1a_15.mem_init3 = 2048'h0000000000006000FFFFFFFFFFFFFFFFFFFFFFF000000000003FE000FFFFFFFFFFFFFFFFFFFFFFF00000000000FFE000FFFFFFFFFFFFFFFFFFFFFFF60000000000FFF000FFFFFFFFFFFFFFFFFFFFFFE40000000000FFC000FFFFFFFFFFFFFFFFFFFFFFE00000000000FFC000FFFFFFFFFFFFFFFFFFFFFFC00000000000F90000FFFFFFFFFFFFFFFFFFFFFE000000000000700000FFFFFFFFFFFFFFFFFFFFF8000000000000780000FFFFFFFFFFFFFFFFFFFFF0000000000000000000FFFFFFFFFFFFFFFFFFFFE0000000000000000000FFFFFFFFFFFFFFFFFFFFCC000000000000040000FFFFFFFFFFFFFFFFFFFFF0000000000000000000FFFFFFFFFFFFFFFF,
		ram_block1a_15.operation_mode = "rom",
		ram_block1a_15.port_a_address_clear = "none",
		ram_block1a_15.port_a_address_width = 13,
		ram_block1a_15.port_a_data_out_clear = "none",
		ram_block1a_15.port_a_data_out_clock = "clock0",
		ram_block1a_15.port_a_data_width = 1,
		ram_block1a_15.port_a_first_address = 8192,
		ram_block1a_15.port_a_first_bit_number = 7,
		ram_block1a_15.port_a_last_address = 16383,
		ram_block1a_15.port_a_logical_ram_depth = 19200,
		ram_block1a_15.port_a_logical_ram_width = 8,
		ram_block1a_15.ram_block_type = "AUTO",
		ram_block1a_15.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_16
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[2]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_16portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_16.clk0_core_clock_enable = "ena0",
		ram_block1a_16.clk0_input_clock_enable = "none",
		ram_block1a_16.clk0_output_clock_enable = "none",
		ram_block1a_16.connectivity_checking = "OFF",
		ram_block1a_16.init_file = "gatinho2_convertido.mif",
		ram_block1a_16.init_file_layout = "port_a",
		ram_block1a_16.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_16.mem_init0 = 2048'h39AB6327107609535C03576D98E58798766C2781DEE5B6F2E4D7E489D2873DE34B6C01DBDF790C9D81E9E97E6F8C2789F2FBFB48C97001643BE4849DBDF4C7C4DE9595AF0258A0E1AC43D69FE1344809DF664EEE1766825EBDE4F1EFCADE3504A2DDC560315EC78163844D9C99AE71F9DD686D746A4DFDA21ED443AA8CF653B8CDF6F112EB533BDEBA8CAFB8F3FA2766FFAFF78D36F9B4A602F3094C54E29891D9B74BF8D6C58F44E4FC53D9C55B0C4AD7178C5E1AD1D1BF496664F20344CA4027F5882671803086F5857693AFBD85956BAAC8529D8C49DD67179B7EAD4B65807945E2AB929CF2E0B1C8849EE52CD7340CA8D10CDB58FAD2251D2EDD3A9FC1DA,
		ram_block1a_16.mem_init1 = 768'hDCDC1B939A21E0B9733FDD2E393583164EB77609E2AC5120122263C32F4A64AF5B38878B3EA9203217CB01A489889EDC9B1F73E50807B4B3B42B43784F5F39DE1DA8125C39A682A40599868B13784D806794309D49380A9E93B486509DE2B3C9,
		ram_block1a_16.operation_mode = "rom",
		ram_block1a_16.port_a_address_clear = "none",
		ram_block1a_16.port_a_address_width = 12,
		ram_block1a_16.port_a_data_out_clear = "none",
		ram_block1a_16.port_a_data_out_clock = "clock0",
		ram_block1a_16.port_a_data_width = 1,
		ram_block1a_16.port_a_first_address = 16384,
		ram_block1a_16.port_a_first_bit_number = 0,
		ram_block1a_16.port_a_last_address = 19199,
		ram_block1a_16.port_a_logical_ram_depth = 19200,
		ram_block1a_16.port_a_logical_ram_width = 8,
		ram_block1a_16.ram_block_type = "AUTO",
		ram_block1a_16.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_17
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[2]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_17portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_17.clk0_core_clock_enable = "ena0",
		ram_block1a_17.clk0_input_clock_enable = "none",
		ram_block1a_17.clk0_output_clock_enable = "none",
		ram_block1a_17.connectivity_checking = "OFF",
		ram_block1a_17.init_file = "gatinho2_convertido.mif",
		ram_block1a_17.init_file_layout = "port_a",
		ram_block1a_17.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_17.mem_init0 = 2048'h80968DF2A98310C68F74E8F7A60B4745B2DCC5C47355F6574365092C27921A79C4EB17C07C1254F89A6B29CD0C0B8A8EA4BB341E0103A34A73B4DC0BACC6E2E2FF0CFDD297BEBC1B7FE13A60161B5273C34C940C053270E90686D311E345D6FEF0C16E4AE6E30D5347B20B9C5D76ED7C19605F0ECF889615AB2172874E9F3C28C3A8C8B30DF40F03C20A5F94208179E7C93A293C1517ECFC704BF034831389A8BACC1124BC3F3371483D59369C3CE259F1FA52E2A9CEECDC4B3D358AC3E0B773036DD6D5017C7F0459C402628180E6312B06E3B3A7A069A8FB522A45C61ECDD20EB5F82251F6278BB4CD05976050128D558E9E6A914B4725BAA566994EB145AB,
		ram_block1a_17.mem_init1 = 768'h9B9546A09AB844504727BBFE5CF6498392DF847C166C3863ECBDF714E3C4E1866263DEFCEE5484A2A571D9410F5B8E6301343CA2EA44901C29EE2C5CC14120A2314E47EC4C6BD474F470D9BDCDB04FCA0AB9EB6B6F44258799963DC54735B24F,
		ram_block1a_17.operation_mode = "rom",
		ram_block1a_17.port_a_address_clear = "none",
		ram_block1a_17.port_a_address_width = 12,
		ram_block1a_17.port_a_data_out_clear = "none",
		ram_block1a_17.port_a_data_out_clock = "clock0",
		ram_block1a_17.port_a_data_width = 1,
		ram_block1a_17.port_a_first_address = 16384,
		ram_block1a_17.port_a_first_bit_number = 1,
		ram_block1a_17.port_a_last_address = 19199,
		ram_block1a_17.port_a_logical_ram_depth = 19200,
		ram_block1a_17.port_a_logical_ram_width = 8,
		ram_block1a_17.ram_block_type = "AUTO",
		ram_block1a_17.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_18
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[2]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_18portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_18.clk0_core_clock_enable = "ena0",
		ram_block1a_18.clk0_input_clock_enable = "none",
		ram_block1a_18.clk0_output_clock_enable = "none",
		ram_block1a_18.connectivity_checking = "OFF",
		ram_block1a_18.init_file = "gatinho2_convertido.mif",
		ram_block1a_18.init_file_layout = "port_a",
		ram_block1a_18.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_18.mem_init0 = 2048'h9AF391C3A5FE2DBC1C59945814B38B9CC70085A08B4A3200B78D935DD844FE5E554C4267F80337864B2C2F1C8C1819F0E08DEDBF545FBD887EFE8B11BA8781FB005D5E85FE6C247A6ABDA3779BA2674054D3F630EEF764E285C726DEA9916488C461948A8216F8EDC948340BB0DDAE1EB4B11277049816971AD6C723B688D17462ACE6F15A26AD8BFAA9F139827DCA7083B14CD7C6092F052B6D51B71746E97029839D90314C41BA2E3B8385B651476CFEBC8D4D8A0D75E592F839088E796C8515B4D7D85C61A0630E9AADC75DEFA15A041428366936BF70B9EB3381824D16811907AE6C3FB2D08F996D2C895CF1A47A2EC6E74A6A96350F5294A0AAD3DD531F,
		ram_block1a_18.mem_init1 = 768'h14996518969D7F970748F9A4B09ED452DD451E10E8ED16BBFA7E2CD34488992F73C5CE4B386F9FD7F66E81915F83C0302DD9BEDD6D48422CD2AA837864A6852A85378ED06132E7A8B98C38E0D8BF3C82CE0BB444FAED8FB832D8C860B536CAED,
		ram_block1a_18.operation_mode = "rom",
		ram_block1a_18.port_a_address_clear = "none",
		ram_block1a_18.port_a_address_width = 12,
		ram_block1a_18.port_a_data_out_clear = "none",
		ram_block1a_18.port_a_data_out_clock = "clock0",
		ram_block1a_18.port_a_data_width = 1,
		ram_block1a_18.port_a_first_address = 16384,
		ram_block1a_18.port_a_first_bit_number = 2,
		ram_block1a_18.port_a_last_address = 19199,
		ram_block1a_18.port_a_logical_ram_depth = 19200,
		ram_block1a_18.port_a_logical_ram_width = 8,
		ram_block1a_18.ram_block_type = "AUTO",
		ram_block1a_18.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_19
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[2]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_19portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_19.clk0_core_clock_enable = "ena0",
		ram_block1a_19.clk0_input_clock_enable = "none",
		ram_block1a_19.clk0_output_clock_enable = "none",
		ram_block1a_19.connectivity_checking = "OFF",
		ram_block1a_19.init_file = "gatinho2_convertido.mif",
		ram_block1a_19.init_file_layout = "port_a",
		ram_block1a_19.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_19.mem_init0 = 2048'h9D747F92DD9C0968A33284C0273C0C1B3B9081888F1BCD96D5F581BBE9A8A8C066707C7840A39D9C0638108E77248615CF15AE806663C1F043476A0A0B02E409C7278D7DCB6F99C44CC1C387E33585778EA0D1868E83CD1C1C5D8DC0CDE1870F0776067A6C91D7012F6394F1A9822D00D9C19C7808EF17AD1C458D035997AFC0921F398D93C731F3F2C6FE674A8AA1206AFFD34C183ADF79B38E61C7E79CF664FD426790D365FEB069873879279E778F1F20E052280EE0D1FA67D13A0D449DF9A63AE71F9E41C049ABDCCB9835E9A2C2CA3267CB4E38CE3F3D83C3E881BE7D96A5FBB1E699AD4F72DE71CAB07881C7ECA72911BE399F30C53C6C9F729CE199CF,
		ram_block1a_19.mem_init1 = 768'hAF2D8ACE83F33AB07870FE35411A8D4D9077824F33DC7946C6636AB078F0FE360284004508F9FDC319FC81320E25CB7031E1C0E78E0E213499E976F9F5FF074199C5F54071C307C73EBE881E37CCF38C87578B29C0196900231F0F8739B8AA4D,
		ram_block1a_19.operation_mode = "rom",
		ram_block1a_19.port_a_address_clear = "none",
		ram_block1a_19.port_a_address_width = 12,
		ram_block1a_19.port_a_data_out_clear = "none",
		ram_block1a_19.port_a_data_out_clock = "clock0",
		ram_block1a_19.port_a_data_width = 1,
		ram_block1a_19.port_a_first_address = 16384,
		ram_block1a_19.port_a_first_bit_number = 3,
		ram_block1a_19.port_a_last_address = 19199,
		ram_block1a_19.port_a_logical_ram_depth = 19200,
		ram_block1a_19.port_a_logical_ram_width = 8,
		ram_block1a_19.ram_block_type = "AUTO",
		ram_block1a_19.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_20
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[2]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_20portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_20.clk0_core_clock_enable = "ena0",
		ram_block1a_20.clk0_input_clock_enable = "none",
		ram_block1a_20.clk0_output_clock_enable = "none",
		ram_block1a_20.connectivity_checking = "OFF",
		ram_block1a_20.init_file = "gatinho2_convertido.mif",
		ram_block1a_20.init_file_layout = "port_a",
		ram_block1a_20.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_20.mem_init0 = 2048'hAAA7FFEC02A1F2106189BA3FC7C00FE03C1F0996D9B3FFCF08027820271B5A3F87807F807F3C19846C363FFE00C37800270ECA7F8783FE007C780C060BFFE7FE80C07E003F65943F8F01FC07FC380671811C27FD010C1E81F840FC3F0E01F80FF878077A3A30977F00840D807B028CFF1E01E07FF0F0173D4789853C1060031938FDA07E1C07C1FC02F0FFBC31DF833F140021B9BBF9C0FE3C0F81F807E0FFBDB2D0DB9F0C9801CC147E87FE381F87F01FC0FF9EF90E197E059C0EC472C283FE383F07E01F81FF8F3FD98EBF02165FFCF18F1FFC703F0FC03E03FC0FCFFF979722004FE9609D3FFCE07E0F407F01F80F8FEFF3FD2660CFCAA19E7FFCE0FE1E0F,
		ram_block1a_20.mem_init1 = 768'h40023000DCA0E38F807F003B811C032E707593B70C038000FCC1938F80FF003983068170C179EE470E037E00FD40F30FC1FE00F80F8F401830EB704F6A407811F481873F81FC07F83F3F282E060FFFB4002070102687AF7FC3E00FF83E3F3231,
		ram_block1a_20.operation_mode = "rom",
		ram_block1a_20.port_a_address_clear = "none",
		ram_block1a_20.port_a_address_width = 12,
		ram_block1a_20.port_a_data_out_clear = "none",
		ram_block1a_20.port_a_data_out_clock = "clock0",
		ram_block1a_20.port_a_data_width = 1,
		ram_block1a_20.port_a_first_address = 16384,
		ram_block1a_20.port_a_first_bit_number = 4,
		ram_block1a_20.port_a_last_address = 19199,
		ram_block1a_20.port_a_logical_ram_depth = 19200,
		ram_block1a_20.port_a_logical_ram_width = 8,
		ram_block1a_20.ram_block_type = "AUTO",
		ram_block1a_20.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_21
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[2]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_21portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_21.clk0_core_clock_enable = "ena0",
		ram_block1a_21.clk0_input_clock_enable = "none",
		ram_block1a_21.clk0_output_clock_enable = "none",
		ram_block1a_21.connectivity_checking = "OFF",
		ram_block1a_21.init_file = "gatinho2_convertido.mif",
		ram_block1a_21.init_file_layout = "port_a",
		ram_block1a_21.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_21.mem_init0 = 2048'hB2C7FFDF008000011A0521FFF8000FFFC01FF18D9FC3FFC3000000211A0559FFF8007FFF803FE183FFC03FF9000000011A02D9FFF803FFFF807FF001F400E7F8800000010263B3FFF001FFF8003FF870380307FC800000810143A3FFF001FFF0007FF87A1D0F277F000002810201D3FFE001FF8000FFE83D3F38013F1000000103031FFFE007FE0002FF003C0FE0453F0000000103F8BFFFC00FFE0007FF003C01DF019F0000000080017FFFC01FF8001FFF001E090F027F00000000803E7FFFC03FF8001FFE000F41D90E3F00000000807EFFFF803FF0003FFC000FBFFFE75720000010407CFFFF007FF0007FFE000F9FEFE33F20000030007DFFFF00FFE00F,
		ram_block1a_21.mem_init1 = 768'h00000000E0C01C7FFF80003FFE1F00E810758C07000000008080BC7FFF00003FFC0700C60079E03B0000000081823CFFFE0000FFF00F808100EB7031604000010902B8FFFE0007FFC03FC860FB0FFF9A000000011B02D0FFFC000FFFC03FC211,
		ram_block1a_21.operation_mode = "rom",
		ram_block1a_21.port_a_address_clear = "none",
		ram_block1a_21.port_a_address_width = 12,
		ram_block1a_21.port_a_data_out_clear = "none",
		ram_block1a_21.port_a_data_out_clock = "clock0",
		ram_block1a_21.port_a_data_width = 1,
		ram_block1a_21.port_a_first_address = 16384,
		ram_block1a_21.port_a_first_bit_number = 5,
		ram_block1a_21.port_a_last_address = 19199,
		ram_block1a_21.port_a_logical_ram_depth = 19200,
		ram_block1a_21.port_a_logical_ram_width = 8,
		ram_block1a_21.ram_block_type = "AUTO",
		ram_block1a_21.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_22
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[2]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_22portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_22.clk0_core_clock_enable = "ena0",
		ram_block1a_22.clk0_input_clock_enable = "none",
		ram_block1a_22.clk0_output_clock_enable = "none",
		ram_block1a_22.connectivity_checking = "OFF",
		ram_block1a_22.init_file = "gatinho2_convertido.mif",
		ram_block1a_22.init_file_layout = "port_a",
		ram_block1a_22.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_22.mem_init0 = 2048'hBEF8003FFF7FFFFE03FC1FFFFFFFF000001FFE7F9FFC003FFFFFFFDE03FC47FFFFFF8000003FFE7FFFFFC007FFFFFFFE03FEC7FFFFFC0000007FFFFFFFFF18077FFFFFFE039F8FFFFFFE0000003FFF8FFFFFF8037FFFFF7E01BF9FFFFFFE0000007FFF85FFFFF880FFFFFF7E03FFBFFFFFFE000000FFFFC2FFFFFEC0EFFFFFFE03FF7FFFFFF8000002FFFFC3FFFFFEC0FFFFFFFE03F87FFFFFF0000007FFFFC3FFDFFE60FFFFFFFF0000FFFFFFE000001FFFFFE1F70FFF80FFFFFFFF0001FFFFFFC000001FFFFFF0FFD9F1C0FFFFFFFF0001FFFFFFC000003FFFFFF07FFFF8E8DFFFFFFF8003FFFFFF8000007FFFFFF07FEFFCC0DFFFFFFFC003FFFFFF00000F,
		ram_block1a_22.mem_init1 = 768'hFFFFFFFF00FFBFFFFFFFFFC0001FFFEFEF8A7FF8FFFFFFFF00FFFFFFFFFFFFC00007FFC7FF861FFCFFFFFFFF01FE7FFFFFFFFF00000FFF81FF148FFE9FBFFFFE01FE7FFFFFFFF800003FF7E0FFF0007FFFFFFFFE03FE3FFFFFFFF000003FFDF1,
		ram_block1a_22.operation_mode = "rom",
		ram_block1a_22.port_a_address_clear = "none",
		ram_block1a_22.port_a_address_width = 12,
		ram_block1a_22.port_a_data_out_clear = "none",
		ram_block1a_22.port_a_data_out_clock = "clock0",
		ram_block1a_22.port_a_data_width = 1,
		ram_block1a_22.port_a_first_address = 16384,
		ram_block1a_22.port_a_first_bit_number = 6,
		ram_block1a_22.port_a_last_address = 19199,
		ram_block1a_22.port_a_logical_ram_depth = 19200,
		ram_block1a_22.port_a_logical_ram_width = 8,
		ram_block1a_22.ram_block_type = "AUTO",
		ram_block1a_22.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_23
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.ena0(wire_rden_decode_eq[2]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_23portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_23.clk0_core_clock_enable = "ena0",
		ram_block1a_23.clk0_input_clock_enable = "none",
		ram_block1a_23.clk0_output_clock_enable = "none",
		ram_block1a_23.connectivity_checking = "OFF",
		ram_block1a_23.init_file = "gatinho2_convertido.mif",
		ram_block1a_23.init_file_layout = "port_a",
		ram_block1a_23.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_23.mem_init0 = 2048'h41000000FFFFFFFFFC03FFFFFFFFFFFFFFE0000060000000FFFFFFFFFC03BFFFFFFFFFFFFFC0000000000000FFFFFFFFFC013FFFFFFFFFFFFF80000000000000FFFFFFFFFC007FFFFFFFFFFFFFC0000000000000FFFFFFFFFE007FFFFFFFFFFFFF80000000000000FFFFFFFFFC007FFFFFFFFFFFFF00000000000000FFFFFFFFFC00FFFFFFFFFFFFFD00000000000000FFFFFFFFFC07FFFFFFFFFFFFF800000000200000FFFFFFFFFFFFFFFFFFFFFFFFE000000000F00000FFFFFFFFFFFFFFFFFFFFFFFFE000000000260000FFFFFFFFFFFFFFFFFFFFFFFFC000000000000000FFFFFFFFFFFFFFFFFFFFFFFF8000000000100000FFFFFFFFFFFFFFFFFFFFFFF0,
		ram_block1a_23.mem_init1 = 768'hFFFFFFFFFF007FFFFFFFFFFFFFE0001000000000FFFFFFFFFF007FFFFFFFFFFFFFF8003800000000FFFFFFFFFE01FFFFFFFFFFFFFFF0007E00000000FFFFFFFFFE01FFFFFFFFFFFFFFC0001F00000000FFFFFFFFFC01FFFFFFFFFFFFFFC0000E,
		ram_block1a_23.operation_mode = "rom",
		ram_block1a_23.port_a_address_clear = "none",
		ram_block1a_23.port_a_address_width = 12,
		ram_block1a_23.port_a_data_out_clear = "none",
		ram_block1a_23.port_a_data_out_clock = "clock0",
		ram_block1a_23.port_a_data_width = 1,
		ram_block1a_23.port_a_first_address = 16384,
		ram_block1a_23.port_a_first_bit_number = 7,
		ram_block1a_23.port_a_last_address = 19199,
		ram_block1a_23.port_a_logical_ram_depth = 19200,
		ram_block1a_23.port_a_logical_ram_width = 8,
		ram_block1a_23.ram_block_type = "AUTO",
		ram_block1a_23.lpm_type = "cyclonev_ram_block";
	assign
		address_a_sel = address_a[14:13],
		address_a_wire = address_a,
		q_a = wire_mux2_result,
		rden_decode_addr_sel_a = address_a_wire[14:13];
endmodule //image_rom_altsyncram
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module image_rom (
	address,
	clock,
	q)/* synthesis synthesis_clearbox = 1 */;

	input	[14:0]  address;
	input	  clock;
	output	[7:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1	  clock;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire [7:0] sub_wire0;
	wire [7:0] q = sub_wire0[7:0];

	image_rom_altsyncram	image_rom_altsyncram_component (
				.address_a (address),
				.clock0 (clock),
				.q_a (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ADDRESSSTALL_A NUMERIC "0"
// Retrieval info: PRIVATE: AclrAddr NUMERIC "0"
// Retrieval info: PRIVATE: AclrByte NUMERIC "0"
// Retrieval info: PRIVATE: AclrOutput NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_ENABLE NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_SIZE NUMERIC "8"
// Retrieval info: PRIVATE: BlankMemory NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_INPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_OUTPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: Clken NUMERIC "0"
// Retrieval info: PRIVATE: IMPLEMENT_IN_LES NUMERIC "0"
// Retrieval info: PRIVATE: INIT_FILE_LAYOUT STRING "PORT_A"
// Retrieval info: PRIVATE: INIT_TO_SIM_X NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
// Retrieval info: PRIVATE: JTAG_ENABLED NUMERIC "0"
// Retrieval info: PRIVATE: JTAG_ID STRING "NONE"
// Retrieval info: PRIVATE: MAXIMUM_DEPTH NUMERIC "0"
// Retrieval info: PRIVATE: MIFfilename STRING "gatinho2_convertido.mif"
// Retrieval info: PRIVATE: NUMWORDS_A NUMERIC "19200"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "0"
// Retrieval info: PRIVATE: RegAddr NUMERIC "1"
// Retrieval info: PRIVATE: RegOutput NUMERIC "1"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: SingleClock NUMERIC "1"
// Retrieval info: PRIVATE: UseDQRAM NUMERIC "0"
// Retrieval info: PRIVATE: WidthAddr NUMERIC "15"
// Retrieval info: PRIVATE: WidthData NUMERIC "8"
// Retrieval info: PRIVATE: rden NUMERIC "0"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: ADDRESS_ACLR_A STRING "NONE"
// Retrieval info: CONSTANT: CLOCK_ENABLE_INPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: CLOCK_ENABLE_OUTPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: INIT_FILE STRING "gatinho2_convertido.mif"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
// Retrieval info: CONSTANT: LPM_HINT STRING "ENABLE_RUNTIME_MOD=NO"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altsyncram"
// Retrieval info: CONSTANT: NUMWORDS_A NUMERIC "19200"
// Retrieval info: CONSTANT: OPERATION_MODE STRING "ROM"
// Retrieval info: CONSTANT: OUTDATA_ACLR_A STRING "NONE"
// Retrieval info: CONSTANT: OUTDATA_REG_A STRING "CLOCK0"
// Retrieval info: CONSTANT: WIDTHAD_A NUMERIC "15"
// Retrieval info: CONSTANT: WIDTH_A NUMERIC "8"
// Retrieval info: CONSTANT: WIDTH_BYTEENA_A NUMERIC "1"
// Retrieval info: USED_PORT: address 0 0 15 0 INPUT NODEFVAL "address[14..0]"
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT VCC "clock"
// Retrieval info: USED_PORT: q 0 0 8 0 OUTPUT NODEFVAL "q[7..0]"
// Retrieval info: CONNECT: @address_a 0 0 15 0 address 0 0 15 0
// Retrieval info: CONNECT: @clock0 0 0 0 0 clock 0 0 0 0
// Retrieval info: CONNECT: q 0 0 8 0 @q_a 0 0 8 0
// Retrieval info: GEN_FILE: TYPE_NORMAL image_rom.vhd TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL image_rom.inc TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL image_rom.cmp TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL image_rom.bsf TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL image_rom_inst.vhd TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL image_rom_syn.v TRUE
// Retrieval info: LIB_FILE: altera_mf
